### ISSUE TITLE
User should be able to close free-form annotation shapes.

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#1015]
Just like other shapes -- rectangles, ovals, polygons -- it seems natural that free form shapes be closed so that the interior area can be recognized on mouseover.

**Comment by beaudet** [comment]
"natural" as in -- it should be easy to close them -- or as in -- they should close by default and we shouldn't allow for open annotation shapes / lines?  I'm sure there's a use case for the latter.

Also, the point in polygon function could just as easily be applied to free form shapes that aren't actually clsoed, if only for the purpose of mouse-over detection - however, overlapping annotations need to be carefully considered with such an approach... e.g. should the smallest area polygon under the cursor should be highlighted?  What if the polygon is self-intersecting, etc.?

**Comment by rsinghal** [comment]
With polygons, a user can choose to close it, by double clicking close to the origin point, which effectively closes the shape and would then fill it, if there is a fill color (and allows a user to hover within the closed shape to see the annotation).  

I think the same approach could be used for freeform, but rather than using double click, I think it would just have to see if the origin and end points are close enough to each other to consider it "closed"?  That's probably too simplistic of a test, but could work in the short term.  @radpet 

However, for both polygons and freeform, some users may not want to close the shape, so we can't remove that functionality entirely.

**Comment by radpet** [comment]
@rsinghal @beaudet It sounds good to me to change them to closed when you draw really close to the origin point. In the future both tools (polygon and freehand) could be extended to auto detect if they are closed or not.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3 annotation creation has been moved out of the core library and into projectmirador/mirador-annotations.
