### ISSUE TITLE
Publish event when slot is activated

### ISSUE THREAD

**Issue by radpet** [ProjectMirador/mirador#1139]
Currently I am not aware of such event that is only fired when something is being done in a particular slot. Do you think it is reasonable to have such? This will allow detecting the current slot that is being used.

**Comment by aeschylus** [comment]
For the most part, I'm all for sprinkling event publications everywhere anyone wants them. What exactly do you mean by "activated"? That the mouse is over it, that one of its child windows' buttons has been pressed? What use case do you have in mind that this would help with, just so I can better understood where I could make a code change?

**Comment by aeschylus** [comment]
I have played around with defining the concept of the "currently selected/active slot" (similar to vim panes), and this was necessary in Mirador 1 to support the "leader/follower" windows for synchronised zooming.

The concept of an "active slot (or active window)" will also be necessary to add keyboard functionality at the window level.

**Comment by beaudet** [comment]
and will also be necessary to add the synchronized pan / zoom between slots back into a 2.x Mirador release I think.

**Comment by radpet** [comment]
@aeschylus  @beaudet  I issued this only because of the 'synchronized pan/zoom" feature but because it  having such information will come in handy. You would be able to visually show the active slot, use this information in external widgets etc.

Anyway, In my opinion the active slot state should give information for the slot which have received any user input last. 
By received user input I mean zoom/pan, menu clicks, everything

**Comment by beaudet** [comment]
@radpet, I think the selection of the "active" slot should be intentional, i.e. a click, rather than just whatever slot the user happened to be hovering over last.  Currently, if you hover over a slot and move the mouse wheel, that slot zooms in / out - that seems too subtle.  Maybe certain actions could be taken on inactive slots without making them the active slot?  In other words, I think it should take something more explicit than mouse motion and scroll wheels to make a slot the "active" one.  Do you agree?  I would think at least a click somewhere within the slot's contents on on the title bar - or at least something as intentional as that.  There would also need to be a scheme developed for defaulting to no active slot or choosing an active slot when Mirador first starts up.   I think it would also help to start by documenting some of the use cases that seem to depend on the need to identify an "active" slot.

**Comment by radpet** [comment]
@beaudet I fully agree with you. 

@aeschylus @beaudet 
One such use case of this functionally used in external system is to have a widget and shows the annotations of the currently active slot :)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
