### ISSUE TITLE
Tests fail locally after installing for the first time

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1167]
After cloning, installing, and setting up, 5 tests fail locally.
all failing tests are in `/mirador/spec/viewer/manifestListItem.test.js`

Is this to be expected or maybe an issue with installed packages/phantomjs?

**Comment by csbailey5t** [comment]
@aeschylus and I started looking at these last week. If I remember correctly, they may be failing due to space issues in the midst of checking those long strings of HTML. I'm going to take a look at them  and see if we can rewrite to check the same thing without worrying about correct numbers of spaces.

**Comment by rsinghal** [comment]
Yes - I wrote it to (naively) do a string compare, rather than a DOM compare.
