### ISSUE TITLE
Do not overlay annotation-creation TinyMCE on top of annotation region of interest

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1260]
![anno1](https://cloud.githubusercontent.com/assets/796990/22899502/e49eaae0-f1df-11e6-83ce-a0987a6c1410.gif)

**Comment by csbailey5t** [comment]
Right now, it looks like the annotation editor defaults to center of the viewport, which does cover annotations made around the central portion of the image. If we wanted to default elsewhere, what would the preference be? 

See: https://github.com/ProjectMirador/mirador/blob/2.1.4/js/src/annotations/annotationTooltip.js#L52-L54

**Comment by beaudet** [comment]
There can also be multiple shapes drawn for a single annotation which might complicate matters.  Panning / zooming can be done, but the controls for pan/zoom need to be accessible since the mouse is bound to drawing annotations in this mode.  So, covering up the lower right corner is probably not the best option.  Mirador can be embedded in a web application and in those cases the real estate afforded to Mirador might be pretty small, so it might not even be possible to avoid overlapping with the annotation shapes.  In such cases, I think having a translucent dialog window would help.  Perhaps if the window border of the annotation dialog is visually enhanced to make it obvious that it can be moved, combined with making the window nearly transparent on mousedown, that might provide enough flexibility. 

However, it might make the most sense to locate the dialog in a tab on the left menu where the annotation layers and navigation will live.  That seems more natural to me and it eliminate the viewport problem - the width of the viewport might shrink when the dialog is opened on the left, but it would not share the same portion of the screen.  That does raise the question of what happens when hovering over an annotation in exploration mode... It would be good for the Stanford UX team to take a quick look at this problem if possible.

![image](https://cloud.githubusercontent.com/assets/77699/23082974/a360c4da-f529-11e6-9a50-a2a1ed3fe4d4.png)

**Comment by rsinghal** [comment]
The TinyMCE box can also be moved around within Mirador, so the user can move it if it covers the region.

**Comment by versae** [comment]
When Mirador is embedded in tiny iframes it might make more sense to show the TinyMCE box as a side panel.

**Comment by csbailey5t** [comment]
If the editor box was placed either within a sidebar or simply made to attach to the left of the window, that could provide an opportunity to better support long annotations, per https://github.com/ProjectMirador/mirador/issues/1261

**Comment by beaudet** [comment]
having a side panel would also make it possible to identify annotations that have been orphaned due to having all associated shapes deleted.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3 annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).
