### ISSUE TITLE
2.3.0 branch has problem deleting annotations.

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1325]
![mirador delete anno bug](https://cloud.githubusercontent.com/assets/145874/23618244/9b1007aa-0244-11e7-8277-e9fbe30022cc.gif)
Haven't done a `git bisect` yet, but at some point in 2.3.0 we created an issue where clicking delete on an annotation popup causes the modal background of the delete confirmation box to be placed on top of the modal itself, making it impossible to click and locking the user in that state.

**Comment by drh-stanford** [comment]
the display of the DialogBuilder is working but it goes inactive immediately afterward, so the callback is never triggered -- https://github.com/ProjectMirador/mirador/blob/2.3.0/js/src/annotations/annotationTooltip.js#L209-L218

**Comment by drh-stanford** [comment]
verified that deleting annotations works in v2.1.3, 2.2.0, and v2.2.0.

**Comment by drh-stanford** [comment]
looks like the bug was introduced in 61213d1

**Comment by drh-stanford** [comment]
i need to pair with someone on this to make further progress...

i don't know the provenance of `css/bootstrap-modal.css` which is where the opacity is being set and the z-index looks like a workaround to bootstrap -- see https://github.com/ProjectMirador/mirador/blob/2.3.0/js/src/utils/dialog-builder.js#L19-L26

**Comment by csbailey5t** [comment]
I'm not sure of a final cause or fix yet, but this seems to be happening because the `shown.bs.modal` event in https://github.com/ProjectMirador/mirador/blob/2.3.0/js/src/utils/dialog-builder.js#L19 is not being triggered. If you go through the delete process and get to where the fade in blocks access to the modal footer, where the "yes" and "no" buttons are, you can trigger the event as written in the code through the chrome dev console and get the correct behavior. (`$('div.bootbox.modal.fade.in').trigger("shown.bs.modal");`)
