### ISSUE TITLE
Different widths for .mirador-container and .mirador-viewer

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#1326]
http://iiif.harvard.edu/miradorapp/ has an instance of Mirador 2.3.0 embedded on a Wordpress site (rather than using an iframe) and as you can see, the normal gray border on the outer edge is cut off.  On this page, .mirador-container has a width of 830px while .mirador-viewer has a width of 860px.

**Comment by rsinghal** [comment]
@gigamorph not sure if you have seen this at all

**Comment by gigamorph** [comment]
The `.mirador-container` element there doesn't seem to have any `position` value. Since `.mirador-container` has`absolute` position and tries to fill the parent, the parent `.mirador-container` should be "positioned" too; otherwise `.mirador-viewer` will fill the next positioned element. For example, I think setting the position of `.mirador-container` to `relative` may fix the problem.

**Comment by rsinghal** [comment]
That fixed it!  Thanks @gigamorph
