### ISSUE TITLE
Remove Bootstrap from Mirador

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1383]
From a cursory look at this, it seems this was only added to provide the modal for deleting an annotation. This is a big set of dependencies for a modal, and I also think the modal, which acts at the document level, should not be global, and perhaps not even a modal.

What are others' thought on this? Bootstrap is a large and opinionated dependency that can conflict with a containing application's version (though much has been done to help with these conflicts).

**Comment by gigamorph** [comment]
I raised the same issue long time ago. Inclusion of Bootstrap in the core initially broke my embedding application because of horrible JavaScript name collisions with Semantic UI I'm using. 

I think I had proposed to either remove dependency on Bootstrap or "officialize" it so everyone will know from the onset that they are stuck with Bootstrap, which seems less desirable.

I'm not sure about being modal. Perhaps it should be.

**Comment by aeschylus** [comment]
Thanks @gigamorph. I think I remember some of this discussion. We ran into some issues locally embedding Mirador in our mirador@stanford service that provides a backend for it. Glad to hear we're not alone.

**Comment by regisrob** [comment]
We removed the Bootstrap css/js from our build since we are already using it in the web application that embeds Mirador

**Comment by rsinghal** [comment]
I'm fine with removing it if we have a decent replacement.

**Comment by mejackreed** [comment]
Can we enumerate all of the places it is being used? 

 - `.modal`

**Comment by mejackreed** [comment]
Resolved in Mirador 3.
