### ISSUE TITLE
Annotation tool toggle is displayed even if there is no annotation endpoint

### ISSUE THREAD

**Issue by csbailey5t** [ProjectMirador/mirador#1423]
If no annotation endpoint is provided, the annotation control toggle still appears even though it does not work, i.e., one can click it but nothing happens. I would recommend hiding the icon if no endpoint is provided, so as not to mislead users.

**Comment by rsinghal** [comment]
It is there if there in the cases where there are manifest annotations.  It can be smarter about knowing if the `annotationsList` array is empty or not for a particular canvas, but the check shouldn't be if there is an annotation endpoint.

**Comment by mejackreed** [comment]
If there are manifest annotations could it then be in a read / non editing mode? Perhaps removing the tools in the panel?

**Comment by csbailey5t** [comment]
Perhaps the issue is in part that the Annotation Toggle is a multi-use button. It always toggles whether annotations are active/viewable on the canvas, and some of the time, depending on settings, also toggles another set of icons/tools. Perhaps my issue is just about documentation and/or sense of consistency in expectation as a developer.

**Comment by rsinghal** [comment]
@mejackreed  The editing icons should only be available when there is an endpoint available.  If that has changed, then it's a regression from previous behavior.

@csbailey5t The idea behind having a single annotation toggle was that Mirador merges annotations from multiple sources (currently manifest annotations and one endpoint, but the idea was that Mirador could handle X number of endpoints) in order to provide a seamless experience to the user (they shouldn't have to click different toggles to see different annotations).  Agree that documentation needs to be a lot better explaining how that works, and perhaps from a user perspective it's better to allow a developer to only show the annotation toggle when there are annotations available on that canvas.  There is an edge case (such as in a course) where multiple users are annotating the same image and we originally had a way to "refresh" the annotations - i.e. re-request annotations from the endpoint and display them.  It was removed and not re-implemented in 2.1 (I think), but it was a useful idea.  Or, instead of removing the annotation toggle completely (which could be confusing to the user to see it come and go), provide feedback to the user that no annotations were found for this image when they turn annotations on.

Documentation would help the developer and understanding the user experience would be beneficial to making this concept less confusing.

**Comment by mejackreed** [comment]
Thanks @rsinghal for the incredible context 👏
