### ISSUE TITLE
No recognition of "paged" viewingHint

### ISSUE THREAD

**Issue by tpendragon** [ProjectMirador/mirador#1440]
When loading a manifest it should read the manifest's viewingHint and do "book" display if it sees "paged"

**Comment by rsinghal** [comment]
Mirador will default to displaying an image using the single image view, but if the manifest has a `paged` viewingHint, then it will allow the user to switch to the book view (otherwise, it disables that view).  It is possible to change Mirador's configuration so it always opens up on book view, but that will apply to all manifests in the Mirador instance, not just for those that are `paged`.

**Comment by rsinghal** [comment]
Actually, thinking about this more - I think the problem is that `viewingHint` can be in a number of different places, and we are only checking for it on the `sequence`.  I assume yours is at the manifest level?

**Comment by tpendragon** [comment]
The "book" view is -available- to choose, but declaring that in the manifest as the viewing hint should make that be the default view that pops up. 

We put it in both places, here's an example manifest: https://plum.princeton.edu/concern/scanned_resources/pdn39zm47v/manifest

**Comment by rsinghal** [comment]
It's been a while, but there were a number of discussions back and forth about what the default behavior should be.  Some wanted it to still default to single image view until the user made the choice, others wanted it to default to book view.  But, in the Mirador configuration, you can force it to always load BookView (if the sequence `viewingHint` is `individuals`, then it will essentially treat it as a single image view`) by adding this:
```
"windowSettings": {
           "viewType" : "BookView",
}
```
This will create some small user experience discrepancies (e.g. to the user, it will look like you are in single image view, but you can't annotation or use image manipulation tools) that need to be fixed, so I am going to create a separate ticket to address those issues in order to create a better user experience.

**Comment by azaroth42** [comment]
I think the spec is pretty clear here for the `paged` viewingHint:

> The canvases represent pages in a bound volume, and SHOULD be presented in a page-turning interface if one is available. 

If the content publisher doesn't want it in a page turning interface, then they should assert a different viewingHint.
