### ISSUE TITLE
Simple thumbnail url for canvas crashes the viewer

### ISSUE THREAD

**Issue by nicolasfranck** [ProjectMirador/mirador#1452]
This manifest
```
http://adore.ugent.be/IIIF/manifests/archive.ugent.be:0002AFCA-9FAD-11DF-BDD4-0559C2C209CF
```
crashes the mirador viewer. See the javascript console.

Apparently the  node module "iiif-evented-canvas" expects every canvas thumbnail to
be an object that has an "@id"? My manifest has a simple url...

Are simple urls not permitted anymore in the newer iiif presentation api?

**Comment by rsinghal** [comment]
This is a bug in evented canvas.  A string is allowed for the thumbnail field.

**Comment by regisrob** [comment]
Yes, I had the same bug with one of my manifests... I am not sure anymore but I think I first changed my manifest to have an object for every thumbnail. 
Then, for the little story, I ran into another issue which, I guess, is related to this if/else block in [thumbnailFactory.js#40](https://github.com/sul-dlss/iiif-evented-canvas/blob/master/src/thumbnailFactory.js#L40), that does not make sense since it requires the thumbnail url to have an extension (png, jpg...). If I remember well, I managed to make my manifest work in Mirador by commenting out this code block directly in mirador.js after the grunt build process :grimacing:

As a side note regarding `thumbnail`, beware of Presentation API 3! https://github.com/IIIF/iiif.io/issues/1147#issuecomment-309120923

**Comment by regisrob** [comment]
Would this be an reliable fix to getThumbUrl() in iiif-evented-canvas library?
Change [thumbnailFactory.js#40](https://github.com/sul-dlss/iiif-evented-canvas/blob/master/src/thumbnailFactory.js#L39) to:
```
  var id = resource['@id'];
  if (id) {
      if (!id.toLowerCase().match(/^.*\.(png|jpg|jpeg|gif)$/)) {
        // it is still a service URL
        var format = getResourceFormat(resource.format);
        if (resource.service) {
            return resource.service['@id'] + buildResourceSize() + '0/' + getTileBasename() + '.' + format;
        } else {
            return id;
        }
      } else {
        // we still don't want the full size
        return id.replace("/full/full/", buildResourceSize());
      }
    }
```
Fixes this issue for the BnF manifests (thumbnail as an object with an `@id` field) and Ghent manifests (thumbnail as a url string)

**Comment by yulgit1** [comment]
added string check to above and it appears to work w/ getty iiif as string as resource:
http://www.getty.edu/art/collection/objects/530/herman-nauwincx-and-willem-schellinks-mountain-landscape-with-river-and-wagon-dutch-1650-to-1675/?dz=0.5533,0.5941,1.12

```
  var id = resource['@id'];
  if (typeof resource === 'string' || resource instanceof String) {
    id = resource;
  }
  if(!id.toLowerCase().match(/^.*\.(png|jpg|jpeg|gif)$/)) { // it is still a service URL
    var format = getResourceFormat(resource.format);
    if (resource.service) {
      return resource.service['@id'] + buildResourceSize() + '0/' + getTileBasename() + '.' + format;
    } else {
      return id;
    }
  }
  else { // we still don't want the full size
    return id.replace("/full/full/", buildResourceSize());
  }
};
```

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
