### ISSUE TITLE
[enhancement] [help wanted] Feature request: allow user to display mouse coordinates

### ISSUE THREAD

**Issue by juliaanvaneijndt** [ProjectMirador/mirador#1503]
Hello,

I was wondering if it was possible to add an annotation tool which would display the pointer coordinates. I've seen that it shouldn't be too hard to implement (https://openseadragon.github.io/examples/viewport-coordinates/), but my coding skills are far too limited to go further (happy to help, though).
The final idea would be to be able to link annotations and TEI markup, as in [this](https://static.chrissparks.org.uk/tei/) tool (TEI Zoner).

**Comment by aeschylus** [comment]
This is certainly possible to build as a plugin, since the mouse coordinates are made available to any containing application rather easily.

Here are some [examples of existing plugins](https://github.com/ProjectMirador/mirador-awesome#plugins) that do other things. These could make a good starting point. The mousecoordinates are available at any time through the API by accessing the a Mirador window's OpenSeadragon instance. However, they will need to be translated into "canvas coordinates", a IIIF-presentation API-specific concept on top of these other coordinate systems.

Can you say more about the context in which you currently use Mirador in order for me to better understand how I might help? Are you looking at objects through the demo site on projectMirador.org, or do you have your own instance up and running? Do you use any existing mirador plugins?

I'm also curious how @jeffreycwitt accomplishes this with his IIIF resources, as I know he has a fairly refined IIIF workflow and has likely encountered this need himself.

**Comment by juliaanvaneijndt** [comment]
Thank you for taking the time for this. There's definitely something to get out of the ruler plugin you are pointing to: I'll try and see if I manage to do something with it.
I am using a local instance of Mirador as a tool for collating manuscripts in the context of a digital edition project. It is pointing to IIIF Manifests from various libraries and a local server for private collection of images. I don't use any other plugin. It is just me and my machine at the moment, but I'd like to deploy that tool in my research team, when I have a functioning workflow.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

Considerable effort went into improving the plugin system for Mirador 3. If you're interested in working on plugin development, please join us at a [bi-weekly Mirador community call](https://iiif.io/community/groups/) or #mirador-dev in [IIIF slack](http://bit.ly/iiif-slack).
