### ISSUE TITLE
Investigate strategy for managing more complex asynchronous process typologies

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1620]
Right now using thunks, we have a working pattern for managing simple requests and allowing the UI to provide synchronous rendering of asynchronous state by storing the request metadata in the redux store. How scalable is this, and what other asynchronous area

## Asynchronous Processes
1. Requesting Manifests
1. Requesting Info.json files
1. Requesting Thumbnails
1. Canceling requests that are no longer required to complete by the user's focus (close the window that was still loading thumbnails)
1. Rendering/Displaying Auth Flow State
1. others...?

## Strategies
1. Continue using a combination of thunks in actionCreators to track request status (essentially split
1. Redux Saga
1. RxJS/Observable Streams
1. `async` + `await`

**Comment by christopher-johnson** [comment]
this is essential to formulate.  There is the potential for an "async request cascade" where hundreds of chained async requests could be required to construct a single rendered manifest in the v3 API.  

The manifest at is most basic form is a list of canvas objects with id and type in the first `Items` array.  The spec does not require the manifest to embed nested items.  The client should be prepared to check for the existence of embedded items and if not present then dereference the object id (with an async action) and subsequently deserialize and normalize the response into state.  This can occur with several different types (e.g. `Canvas`, `AnnotationPage`, `Annotation`, `Range`, etc.)  

This is more likely to occur in the AnnotationPages `Items` array, where there may be both a page that contains embedded painting annotations and distinct `AnnotationPage` ids that must be dereferenced to get annotations with other motivations (similar to "`otherContent`" in v2).   

It is necessary to understand how to abstract fetch action dispatching so that the rendering components can be agnostic to the resolution, reduction and evaluation of the API responses.  The rendering component itself should not contain any business logic that does conditional fetch dispatch as I suspect that this may negatively impact performance and usability.
  
Example:
```javascript
if (items) {
  handleItemsResponse(items);
} else {
  fetchItems(objectURI);
}
```
It should just get a denormalized and contracted object or value (or null) from its selector.  IMO, the business logic of async response handling and reduction/resolution should be clearly separated from the rendering components...

**Comment by aeschylus** [comment]
Might be useful soon: https://www.robinwieruch.de/redux-state-keys/

**Comment by christopher-johnson** [comment]
Error handling using try catch blocks.

**Comment by mejackreed** [comment]
Closing this ticket, we have been using strategy 1 right now. Let's reopen if new options come up or there are new things to discuss.
