### ISSUE TITLE
Export React components to be usable independently

### ISSUE THREAD

**Issue by bitzl** [ProjectMirador/mirador#1625]

**Comment by sdellis** [comment]
Also, set up integration test that uses a React component that is not Mirador

**Comment by jbaiter** [comment]
Is this related to #1611?

**Comment by mejackreed** [comment]
Kind of, I think this ticket may need some more details about what the desired external API of a component would be.

For instance, a user story that could help inform this ticket:

As a Mirador adopter who has my own React application, I want to import a `Workspace` so that I can provide a custom Mirador experience.

I don't know more details about this than that above, and it would be great to be targeting an intended use case. cc @christopher-johnson
