### ISSUE TITLE
Spike on rolling our own windowing system

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#1662]
There's a demo of this in the [relevant PR](https://github.com/ProjectMirador/mirador/pull/1724), sort of. There are a few other elements of the proposed custom windowing behaviour to implement there, namely the large ("infinite"), pan-able workspace area. There are a few ways to implement this, and @sdellis and I are going to try to document these considerations here.

We need something like:
![overlapping windows - workspace shift](https://user-images.githubusercontent.com/145874/51943985-b0a02b00-23cf-11e9-8aa4-6e7a3cf6ed13.gif)
where the orange box is the browser viewport (or mirador topmost viewer container), the blue things are windows, and the outer dark red box is the workspace element, which is translated far to the left and top of the browser viewport to provide space for the windows to occupy. This margin value would be applied to all the windows' 3D transform style attribute (as children of the workspace element).

Another diagram showing this setup: (Note that the workspace "artboard" is shifted up and to the left so there is enough space for its windows, which are child elements).
<img width="970" alt="screenshot 2019-01-29 at 2 14 39 pm" src="https://user-images.githubusercontent.com/145874/51944222-59e72100-23d0-11e9-88f2-da270400ee9b.png">
Here's a gif screencapture of this being done in the browser console with the element style panel. A css scale transform is applied to the workspace element based on the bounding box of all open windows within the workspace "artboard" element, accomplishing the "exposé" feature:
![overlapping windows - expose](https://user-images.githubusercontent.com/145874/51943076-7766bb80-23cd-11e9-9c7b-4edb122232f8.gif)

**Comment by aeschylus** [comment]
@jvine @ggeisler 
Does this seem right? Do you imagine the panning behaviour apply to any of the other workspace types (if we go that direction)?

**Comment by jvine** [comment]
My concept of the "infinite" workspace has been that the workspace starts out being the size of your Mirador viewport, until you push something outside of it, then it expands as much as it needs to - so the workspace is only as large as the layout you currently have in it, and panning never extends beyond the actual open windows. Exposé in that context is only available when the content expands beyond the viewport, and it shrinks the content to fit the viewport. 

That means the expose would look less like this:
<img width="668" alt="screen shot 2019-01-29 at 5 18 40 pm 2" src="https://user-images.githubusercontent.com/6945691/51951670-582a5700-23ea-11e9-883d-e42d07f330d5.png">

and more like this:
<img width="668" alt="screen shot 2019-01-29 at 5 18 40 pm 2 copy" src="https://user-images.githubusercontent.com/6945691/51951676-5a8cb100-23ea-11e9-9d70-2035e123c681.png">

I don't know if it's an important distinction. But if the workspace is always massive, then it seems like pan is always necessary, even if it means you can lose sight of your open windows. (Though I guess panning into blank space allows you to open a new window into an empty viewport.)

When windows are auto-arranged into columns, my expectation is that the columns would fill the viewport horizontally and scroll vertically, but that the user could pull a window out to the side to again expand the workspace and panning would apply.

The only exception would be when windows are tiled to fit the workspace - in that instance we're assuming the user's intent is to fix the arrangement, and we'd need to provide some other way to break out of that arrangement. (Or maybe it's just another arrangement, like columns, and the user can choose to freeze it - opposite of assuming it's frozen and the user finds a way to break out of it.)

Maybe that's a useful metaphor. Workspace is elastic rather than infinite, and its border can be frozen by user action. @ggeisler interested in your thoughts.

**Comment by aeschylus** [comment]
This is helpful. I think I may have introduced confusion into the interaction discussion by including implementation details. To the user, they use space as needed, since their viewport begins in the center and they can't see the edges of the artboard. As far as they know the artboard isn't a thing, and they can keep panning and dragging windows around as they wish. Expose just nicely frames the bounding box of all existing windows, not showing they whole art board (which must be extremely large, as an implementation detail, to avoid having to recalculate three layers of mutually-dependent coordinates each time the user moves a window outside further afield of previous windows). This "zoom out only enough to show all currently open windows nicely in the viewport" is what I intended above, but perhaps showed too much whitespace.

**Comment by aeschylus** [comment]
After spending some time implementing the above, I think my existing overlapping windowing implementation is mostly garbage and should be thrown out. There are several useful, fairly low-level libraries providing good primitives to do another try here. Popping these in for tomorrow:

- https://github.com/bokuweb/react-rnd for the resizable window implementation (the callback api should allow it to easily hook into the redux state management that's already hooked up there)
- https://github.com/mzabriskie/react-draggable for the artboard implementation

**Comment by ggeisler** [comment]
As we discussed yesterday, I think I'm generally in agreement with @jvine's conception of the workspace, in particular the metaphor of it being elastic rather than infinite. However, in the comments above there are a few things I'm not sure I entirely understand.

One issue is we're introducing new terminology and I'm unsure if we are all talking about the same thing with these new terms. 

- Is "artboard" the same as "workspace viewport"?
- Is "auto-arranged into columns" the same as "tile view" (workspace menu option "Tile all in frame")?
- How is "windows are tiled to fit the workspace" different from "tile view"?

So, agreed on elastic workspace, but am unsure about the idea related to freezing the workspace. I guess I'm not clear why this needs to be an explicit thing the user has to be aware of (if that is the suggestion); I've been thinking the workspace is initially tiled, if the user rearranges windows the workspace is now freeform, and if the user selects the "Tile all in frame" option at any point the workspace returns to tile mode. And those "modes" are really only relevant when the user adds new windows to an existing workspace, because it affects how the new windows are added per #1705 (although the user still does not need to know what mode they are in; it just affects how they see the new windows that appear in the workspace).

Maybe @jvine's suggestion for freezing is we add an option for the user to say they want to stay in tile mode, so when they move windows around they snap to the existing column arrangement?

**Comment by ggeisler** [comment]
Actually I should've been clear: I think it was @aeschylus who introduced the "artboard" terminology. I just wanted to make sure he means the same thing as when we refer to the workspace viewport.

Yeah, "tile all in **frame**" doesn't accurately describe what we've been thinking. I didn't get mixed up by the "frame" part, though. 

My confusion was based on: 

> We later discussed an additional "tile" option that would fit all the open windows into the workspace viewport in a grid layout

I think this is what I was trying to call "slot view" to prevent us from having to talk about two different types of "tile" view (not suggesting "slot" as a user-facing term but a term for us to use because it is basically the same as Mirador 2's slot-based workspace arrangement).

So, if I'm correct in assuming we're talking about "tile view", "free form view", and "slot view" as the three relevant workspace arrangements, then my confusion is cleared up. _However_, I also thought we needed to resolve the windowing system decision before deciding we need a "slot view". (Under the assumption we shouldn't add more workspace types/views than absolutely necessary.)

**Comment by mejackreed** [comment]
I think this should have probably been closed in #1815, some good info here
