### ISSUE TITLE
Distinguish between presentational and container components and keep them in seperate folders

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#1727]
I suggest to distinguish between presentational and container components and keep them in seperate folders. This follows a common pattern in the react-redux world (see for example [here](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)). 

In our case container components are those that we get via `connect()` and `miradorWithPlugin()`. Presentational components are the pure react components that render ui elements and are not aware where their props come from.

### Example

src/components/Window.js

```javascript

class Window extends React.Component {
  // ...
}

Window.propTypes = {
  // ...
}

export default Window
```

src/containers/Window.js

```javascript
import Window from '../components/Window'

const mapStateToProps = state => { ... }
const mapDispatchToProps = dispatch => {}

export connect(mapStateToProps, mapDispatchToProps)(miradorWithPlugins(Window))
```

src/components/Workspace.js

```javascript
// In our application code we will normally import 
// the connected components from the 'containers' folder.
import Window from '../containers/Window'

class Workspace extends React.Component {
  render() {
    return  <Window foo="bar" />
  }
}
```

__test__/src/components/Window.test.js

```javascript
// In our unit tests we can import the unconnected component
// for shallow rendering from the 'components' folder.
import Window from '../../../src/components/Window'
```

### Pros
- separation of concerns
- increased readability
- increased reusability
- reasonable component naming due to simpler import and export patterns (getting rid of the 'connected' prefix for the components)

### Cons
- switching between the two files while working on a component
- scrolling up and down to see if a component was imported from './components' or './containers

**Comment by aeschylus** [comment]
I'm very interested in settling on a solution in this space, since I think it will calm a lot of anxiety about doing the right thing and let us develop with greater confidence. Here are some opinions or observations from my react/redux experience so far:

- When adding new child components, or changing their location within the hierarchy, it is annoying to have to explicitly update the prop passing code in multiple places. For example, if I edit a component to display new information that is available in the store, I have to edit that element's container component in order to gain access (I think this is what you are getting at with your second "con" bullet). If that component is nested, I have to pass the prop all the way down across 3 or 4 files.
- I agree it would help reusability, since we can directly instantiate components in a non-connected environment such as a [cosmos](https://github.com/react-cosmos/react-cosmos) or [storybook](https://github.com/storybooks/storybook) dashboard.
- pure functional components are much easier to test and by definition cannot have bug-causing side effects. The data involved in their operation is completely encapsulated and always clearly visible in the function arguments and return values. This is not always realistic, as I'll note below, but it is the whole point of using redux and react: the state is immutable and the rendering system (react) is purely functional (unless we introduce side-effectful code).
- We cannot (or at least have not yet found a way to) make pure functional components integrate with the plugin system. How do we generically inject DOM children or plugin components from outside the running viewer instance using pure functional components? Does this mean we will never have any non-"container" components?
- I am in favour of moving away from the `connectedBlahBlahBlah` import naming scheme, as this smells of JAVA "[EnterpriseFizzBuzzFactoryFactoryConstructor()](https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/tree/master/src/main/java/com/seriouscompany/business/java/fizzbuzz/packagenamingpackage/impl/factories)" - an implementation detail being incorporated in the name.

**Comment by mejackreed** [comment]
I really like the thought put into this, and think this type of organization will be immensely useful moving forward.

I had a similar reaction as @aeschylus about the plugin system. Can we distinguish between what should be pluginable (only a container component) and presentational components? I think so. Right now most of everything is container or mixed, but we have some purely presentational components peaking out (`CompanionWindow`). It seems like in this case, that our container components would be pluginable, and the aim of our presentation components would be for reuse internally and for adopters.

I do also have a similar concern mentioned in the cons list about switching back and forth between the components.

**Comment by charbugs** [comment]
@aeschylus I think thats an important point. For me, Redux is a pattern that enables functional javascript in large applications. And to have pure functional components would perfectly fit to this approach. But for now I know to less about React to see how we can circumvent or replace the features that come with component classes. 

([click](https://docs.spring.io/spring/docs/2.5.x/javadoc-api/org/springframework/aop/framework/AbstractSingletonProxyFactoryBean.html) for some more java fun)
