### ISSUE TITLE
Do we need to use derived state

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#1734]
From @aeschylus:
> Can you provide a little more context for this. Why is derived state even being used?

> https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

> Happy to merge now, since this is all in flux, but maybe we can ticket a refactor of this. It seems like we should be able to set up the redux state differently in order to avoid this. For example, would this go away once manifesto is removed from the redux store? I might be missing something obvious, bu at what point is the manifest ever changing in the lifecycle of a window?
> @jbaiter @charbugs - opinions?

Context: https://github.com/ProjectMirador/mirador/pull/1730

**Comment by charbugs** [comment]
I think we don't need and should not use `getDerivedStateFromProps` because `mapStateToProps` and `mapDispatchToProps` cover this use case. The signatures of this two functions are:

`function mapStateToProps(state, ownProps?) => object`
`function mapDispatchToProps(dispatch, ownProps?) => object`

I.e. within this functions we can use the passed props of the component to get data from the redux state. 

Example: Inject the manifest to the component based on the manifest id that is passed from the parent component:

```javascript
function mapStateToProps(state, props) {
  return {
    manifest: state.manifests[props.manifestId]    
  }
}

// ...

export  default connect(mapStateToProps)(MyComponent)
```
