### ISSUE TITLE
Window sidebar open/close behaviour

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#1853]
Sidebar currently has just one option implemented, using an icon button to open the metadata panel. Icon button does not indicate selected status when its associated panel is opened.

Intended behaviour for the window sidebar is similar to a [tab bar](https://material-components.github.io/material-components-web-catalog/#/component/tabs). (Not clear if MUI's tab bar component allows for vertical tabs, though.)

- [ ] ~1. When the sidebar menu is first opened, the info panel is open be default.~ (**updated March 5 2019**; split to #2059 )

<img width="400" alt="no tab selected" src="https://user-images.githubusercontent.com/5402927/53828898-be4b5200-3f33-11e9-81ff-c43a5d4141e1.png">

- [x] 2. When the user clicks an icon, the associated panel opens, and the icon is in "active" state.

<img width="400" alt="active tab icon" src="https://user-images.githubusercontent.com/6945691/52676220-4a8eca00-2ede-11e9-9d82-cadb0a1ca2cb.png">

- [x] 3. The icon is **not** a toggle: re-clicking an active icon does not hide or close the panel. The open panel has a "hide" toggle: 

<img width="400" alt="hide panel widget" src="https://user-images.githubusercontent.com/6945691/52676372-c8eb6c00-2ede-11e9-8be8-a4dd5cec6b39.png">

- [x] 4. Clicking that toggle hides the panel, but does not change the active state of the icon. User can click the toggle again to un-hide the panel, which remains in exactly the same state as the user left it: scrolled down, filter applied, options selected, etc.

<img width="400" alt="un-hide panel widget" src="https://user-images.githubusercontent.com/6945691/52676471-1bc52380-2edf-11e9-8986-d77d74adf8c7.png">

(Note that the toggle was not shown in this state in previous designs; that was an error.)

- [x] 5. While one icon/tab is selected, user can hover over other icons without changing the active state of the selected icon. 

<img width="400" alt="icon hover state" src="https://user-images.githubusercontent.com/6945691/52676236-54b0c880-2ede-11e9-8044-471a9c3e00c3.png">

- [x] While the panel is visible, clicking:
- the active icon does _not_ hide or close it
- any other icon replaces its content
- the "hide" toggle hides it

- [x] While the panel is hidden, clicking: 
- the "hide" toggle shows the panel in its last open state
- the active icon shows the panel in its last open state
- any other icon opens the panel to that content

- [ ] Note that the panel is on the same surface as the image, and the image should be re-centered (zoom level maintained) in its narrower area when the panel is open.

**Comment by jvine** [comment]
@sdellis: Question about accessibility for the sidebar show/hide feature:  it's purpose is to increase the visible area available for the image. Given that, do we need to signal to a screen-reader that the panel content has been hidden or made visible? I'm wondering if it's useful to make perceivable a feature that has no real purpose in that context.

**Comment by camillevilla** [comment]
This is visually coherent, but I think this ticket will introduce some tricky things into state. 

> While the panel is hidden, clicking:
>    * the "hide" toggle shows the panel in its last open state

I would propose implementing this part of the ticket a little farther down the road. We should at least have `compact list` AND `thumbnail list` implemented for the Canvas Navigation panel.
<img width="316" alt="screen shot 2019-02-12 at 8 08 48 pm" src="https://user-images.githubusercontent.com/5402927/52686464-ab2ffe00-2f02-11e9-89a7-fcf41c188ad8.png">

---
@jvine  I'm also a little confused about this part of the ticket:
> While the panel is visible, clicking:
>    * the active icon does _not_ hide or close it

<img width="400" alt="hide panel widget" src="https://user-images.githubusercontent.com/6945691/52676372-c8eb6c00-2ede-11e9-8be8-a4dd5cec6b39.png">

In its initial state, clicking on the icon sets it to `active` AND toggles the panel `open`. If the user clicks on the icon again, will they be confused if the icon doesn't hide the sidebar? 

--- 
Items that could be split out of this ticket (if this visual style suffices):
- enhance icon selection style so that `primary`: `light` color is applied to the div background and `primary` color is applied as a `border-right` (🎟)

**Comment by jvine** [comment]
I'm concerned that the implementation direction so far is assuming a behaviour for the sidebar that is not intended and might be hard to retrofit. 

The hamburger menu on the window top bar opens and closes the sidebar, resetting everything to its initial state. Other than this, there is no "close" action; it's just "hide".

The "hide" behaviour minimizes the size of the sidebar, or removes it from the visible elements on screen, but does not close it. Look at Google Maps for an example of this behaviour. Their "collapse" toggle moves the panel off-screen to increase the visible map area, but this action does not affect the content of the panel at all. The "expand" action restores the panel's position on the screen; it doesn't re-open the panel in its original state.

Our version of the sidebar is a bit different because the icons remain visible even when the content is not. The intent of this is that, as the user navigates through canvases, the icons can indicate whether certain attributes are present for that canvas - e.g. this canvas has annotations, this one has layers, this one has none. 

> In its initial state, clicking on the icon sets it to `active` AND toggles the panel `open`. If the user clicks on the icon again, will they be confused if the icon doesn't hide the sidebar?

Can we restate this as "toggles the panel `visible`"? I think the open/close terminology has been confusing.

In normal tab-bar behaviour, clicking a tab typically displays the content for that tab, and may open or expand an area for the content if there is not one present. Clicking a tab in its active state never hides or closes that tab. Since there will be an explicit "hide" affordance present, I would prefer to start with the standard tab behaviour, and consider layering on the icon/toggle behaviour later if usability requires it.

**Comment by jkeck** [comment]
I was talking about the hide vs. re-render behavior.  Currently we remove the panel content from the DOM entirely when it is hidden (because react is cool and it's super easy to do that), but really, we should be using MUI's attributes in some of these cases.

I wouldn't be super worried about the current implementation, it was intended as something to react to.  We're sussing out some good acceptance criteria, which will allow us to make better implementation decisions.

**Comment by camillevilla** [comment]
After discussing this ticket with @jvine @cbeer and @charbugs, we have reaffirmed that Material UI's `<Tabs>` component is ideal for the behavior described above. 

[Demo: tab bar component](https://material-components.github.io/material-components-web-catalog/#/component/tabs)
Pay attention to keyboard nav behavior.

![tab-bar-demo](https://user-images.githubusercontent.com/5402927/53828138-ae327300-3f31-11e9-91c2-5f4eae733f54.gif)

https://material-ui.com/demos/tabs/#tabs

**Comment by glefi** [comment]
@camillevilla I've already had have a look at the tabbar control, but there seems to be no possibility to arrange the tabs in a vertical way. I've found some workarounds, but this wouldn't be conform to the principles of material-ui. @jvine @ggeisler what do you think?

**Comment by cbeer** [comment]
I can take a look into this today (having just tweaked the appbar to have a vertical mode...) if you want.

**Comment by glefi** [comment]
@cbeer this would be great!
