### ISSUE TITLE
Handle HTML from IIIF metadata

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#1854]

**Comment by charbugs** [comment]
Can you say how html should be handled? There is a wide range from ignoring all to rendering all. Also, can you provide a fixture for that.

**Comment by jkeck** [comment]
This ticket is intended to figure those details out.  I don't have all those answers, and I think it's up to this group to figure out what that means (and how Mirador handled it in the past would be a good start).

I noticed when implementing #1855 that raw HTML was being rendered in the panel, which I assume is not the desired behavior.

**Comment by charbugs** [comment]
Some time ago I worked on an react application that dealt with this problem. There where text messages that came from third party APIs and this texts should be rendered in the UI. It should be possible to allow some elements to render but for safety reasons not the entire HTML set. I used a [HTML santizer](https://www.npmjs.com/package/sanitize-html) for this problem. You can specify a limited set of elements (and even attributes) that you consider harmless for your application. Each other elements will be striped from the text. 

By default, react will not render HTML that you pass as text content to components. But there is this `dangerouslySetInnerHTML` attribute of react that you can use to circumvent that behavior.

### Questions

1. What does the IIIF docs say about HTML content in manifest fields?
2. How is HTML content handled in Mirador 2?
3. Do we want to render HTML that comes with manifests?
4. If so, what set of elements should be allowed, which not?
5. How does this interfere with our design?
6. Do @jvine and @ggeisler already have thoughts on that?

**Comment by mejackreed** [comment]
2. Mirador 2 implementation of sanitization: https://github.com/ProjectMirador/mirador/blob/v2.7.0/js/src/utils/utils.js#L272-L280

**Comment by ggeisler** [comment]
1. The Presentation 2 spec has a section about HTML markup that says "Minimal HTML markup may be included in the description, attribution and metadata properties. It must not be used in label or other properties." (https://iiif.io/api/presentation/2.1/#html-markup-in-property-values) So I think we should display HTML that is found in those properties. 

4. That section of the API (the same section in the Presentation 3 spec looks very similar) also says:

> Clients should allow only a, b, br, i, img, p, and span tags. Clients may choose to remove any and all tags, therefore it should not be assumed that the formatting will always be rendered.

6. Based on the above, maybe the design-oriented question here is whether we are worried about whether the allowable tags might affect display. I think it might depend on the property. 

For example, all of the allowable tags other than `img` seem reasonable to show when they appear in the description and metadata properties. But if we are using the attribution property as the source of the institution line shown in the mockups in #1834, the `br` and `p` tags could cause formatting trouble (because we assume a relatively short line or two at most for an attribution). And the `img` tag in any of the three properties could potentially cause formatting trouble (e.g., several images in a description or metadata property could make a Window's About panel look much different than we intend).

But maybe we just start by whitelisting all of the tags allowable by the spec (a, b, br, i, img, p, and span tags) and then just test on a bunch of different manifests and see what the results look like? And then we can make a more informed decision of which, if any, tags we want to further restrict in one or more of the three allowable property contexts.
