### ISSUE TITLE
Mosaic mode --> draggable windows

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#1856]
We are currently able to resize windows, but unable to arrange where they appear in the workspace. `react-mosaic` allows us to drag windows around and dynamically split other windows.

![mosaic-window-split](https://user-images.githubusercontent.com/5402927/52615775-2f26af00-2e4b-11e9-95fd-21c740c5f636.gif)

A first stab at this work would involve analyzing the [react-mosaic docs](https://github.com/palantir/react-mosaic) and reporting back to the team re: feasibility. 

### Out of Scope
- Other `react-mosaic` functionality: (e.g. 
  - `replace`, `split`, `auto-arrange` etc. (will loop back w/ design team)
  - `expand` (Possibly related to #1703)

### Resources
- [Interactive designs](https://github.com/ProjectMirador/mirador-design/wiki/Mirador-3-Interactive-Designs)
- Mosaic mode design #1788

**Comment by mejackreed** [comment]
I filed a ticket upstream to see if what I want to do is possible: 

https://github.com/palantir/react-mosaic/issues/98

I have a basic implementation working, but it does not seem that desirable since the "toolbar" is separate from our `WindowTopBar`

![dragging things](https://user-images.githubusercontent.com/1656824/52819266-17774280-3066-11e9-9cac-33aaa721f372.gif)

I'm going to wait and see if the react-mosaic team responds before moving forward.
