### ISSUE TITLE
Implement Right to left navigation

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#1881]
Likely implementation places:
 - [ ] ThumbnailNavigation
 - [ ] WindowViewer
 - [ ] ViewerNavigation

**Comment by hmmlsystems** [comment]
I’ve been seeing the announcements and am excited for the impending release of version 3.

In doing some testing with vHMML manifests, I’ve noticed that the current version doesn’t seem to be loading our Right-to-Left Manuscript Manifests. Are there plans for this to be a part of 3? This is extremely important for many of our vHMML manuscripts.

Interestingly, R-to-L seemed to be working in alpha 2, or at least images were loading.

For reference, I created 3 codepens to do testing. The first has a vHMML left-to-right manifest using beta 8 (working): https://codepen.io/hmmlsystems/pen/wvKYOww

The second has a vHMML right-to-left manifest using beta 8 (not working): https://codepen.io/hmmlsystems/pen/LYpgaYr

The third has a vHMML right-to-left manifest using alpha 2 (images loading): https://codepen.io/hmmlsystems/pen/zYvmbYE

Many of our vHMML manifests aren’t “open” due to the contracts we have with some of our partners. This means that they won’t work in external Mirador viewers. But for testing here are a couple more links (PURLs) to open manifests.
Basic: https://w3id.org/vhmml/readingRoom/view/510545 
Manifest: https://www.vhmml.org/image/manifest/510545

Right-to-Left: https://w3id.org/vhmml/readingRoom/view/518642 
Manifest: https://www.vhmml.org/image/manifest/518642

Any help/advice would be appreciated. Are we missing something in our manifests now for Mirador 3? Or has it yet to be implemented?

Thanks!

**Comment by cbeer** [comment]
Thanks for the report, @hmmlsystems. It looks like Mirador 3 is tripping over the literal `null` values in your manifests.  I've extracted your report to its own issue (#3035) and we'll get it fixed soon.

**Comment by hmmlsystems** [comment]
Wow! Thanks for the quick work @cbeer and setting up the new issue. Thank you!

**Comment by mejackreed** [comment]
Now this seems resolved with #3035 being 🚢 and RTL implemented.
