### ISSUE TITLE
"Reset zoom" should fit image to window

### ISSUE THREAD

**Issue by jvine** [ProjectMirador/mirador#1976]
When you click the "Reset zoom" icon on the canvas, it zooms the image in to a degree that's not humanly achievable, and seems broken. Intent is that it should either fit the image to the current window, or revert to the original zoom level from when the window was opened. For consistency, the design preference is to fit to window, which seems to be the OSD default behaviour in M2.

**Comment by jkeck** [comment]
Possibly related when tackling this: #1818

**Comment by jkeck** [comment]
Also, a little context since I poked at this briefly.  We're setting the Zoom level to `1`, however the "Zoom" at initial load may not be `1` however and can be a much smaller number (it is based on a lot of factors).  One option would be to persist the original x, y, zoom somewhere and have the Zoom Reset button reset to that.

However; this may not ultimately be what we want (for the reasons outlined in #1818) so the refactoring described there may be the best way to go about doing this.

**Comment by mejackreed** [comment]
I think we might want to add a method onto `OpenSeadragonViewer` that could set itself to the initial bounds. That way the method could be passed through or accessed by external components rather than a new component needing to figure this out.

I wonder if something like this could work https://github.com/ProjectMirador/mirador/blob/master/src/components/OpenSeadragonViewer.js#L62
