### ISSUE TITLE
enhanced plugin system: Create mechanism for negotiating the hierarchy of plugins

### ISSUE THREAD

**Issue by camillevilla** [ProjectMirador/mirador#2188]
Follows on from work in #2098 
Pre-requisites: #2184, #2186 , #2187

**Comment by charbugs** [comment]
Here's my idea for handling mutliple plugins that targeting the same component:

### Relationship

* Their can be only one **delete** plugin per component and this plugin makes all other plugins for this component obsolete.
* Their can be only one **replace** plugin per component and this plugin makes all other plugins for this component obsolete.
* Their can be only one **wrap** plugin per component.
* Their can be mutliple **add** plugins per component.

### Precedence of modes

1. delete
2. replace
3. wrap
4. add

### Precedence of plugins of the same mode

* first come, first serve

### Examples

a) 

**plugin A** target: Window, mode: add
**plugin B** target: Window, mode: replace
**plugin C** target: Window, mode: delete

--> Only plugin C will be applied

b) 

**plugin A** target: Window, mode: add
**plugin B** target: Window, mode: replace

--> Only plugin B will be applied

c)

**plugin A** target: Window, mode: add
**plugin B** target: Window, mode: add
**plugin C** target: Window, mode: wrap

--> All plugins will be applied

d)

**plugin A** target: Window, mode: replace
**plugin B** target: Window, mode: replace

--> Plugin A will be applied 

e)

**plugin A** target: Window, mode: add
**plugin B** target: Window, mode: add
**plugin C** target: Window, mode: wrap
**plugin D** target: Window, mode: wrap

--> Plugin A,B,C will be applied

**Comment by charbugs** [comment]
I just realized that there is a simpler solution for that. It is acutually sufficent to have an *add* and a *wrap* mode because deleting and replacing are special cases of wrapping. And I think that it's accurate (at least at this point of the project) to say that wrapping always has priority over adding. This is because we're going to alow adding plugins only to some special places. That is, the only conflict could be that a plugin tries to wrap a component that is such a place.

So the order should be that:

* Their can be only one **wrap** plugin per component and this plugin makes all other plugins for this component obsolete.
* The first **wrap** plugin will be served first.
* Their can be mutliple *add* plugins per component.
