### ISSUE TITLE
Change how annotation selection behaves

### ISSUE THREAD

**Issue by jkeck** [ProjectMirador/mirador#2264]
Currently, annotations are added to a list of selections specific to each canvas.  The intent of the feature is to change the selected annotation from click to click (as more of a navigational construct).

A nice feature may be to allow a canvas to have multiple annotations selected at once (using some modifying keys like shift or command).

#2257 was created and pushed up to begin to think through the implications/behavior of this kind of select (or to decide to abandon all-together for a simple single select).

**Comment by ggeisler** [comment]
@jkeck After working through some mockups exploring how multiple selections with modifier keys might work, @jvine and I think the best approach overall is to go with one of your suggestions: 

> abandon all-together for a simple single select

So:

- No modifier keys; instead go with your original approach where each click on an annotation adds it to the selection list. If the user clicks an already selected (and thus highlighted in the panel) annotation, that would remove it from the selection list.

- Add a bottom border to each annotation, same as we do in the TOC panel for each list item

Below are some additional related enhancements, which go beyond your original focus on the selection behavior in that they introduce changes to how the annotations are represented on the canvas (really just distinguishing between selected and highlighted annotations). If you'd rather separate these into a new ticket I can do that.

## Terminology

**Highlighted** annotation - purpose is to indicate to the user where on the canvas the annotation is, but user has not indicated this is an annotation they care about or want to select. 

- Shown on canvas with blue border (#00BFFF - fixed color; doesn't change with theme)
- Indicated in panel with hover/focus highlighting (the lighter gray used in places like the workspace menu, for example). So when a mouse user hovers over an annotation item in the panel list, or a keyboard user moves into an annotation item (I think arrows into, though keyboard nav in the panel probably isn't working yet), the annotation item area is highlighted in gray. 

**Selected** annotation - purpose is to indicate to the user the annotation(s) they have added to the selection list (annos of interest). 

- Shown on canvas with yellow border (current color)
- Indicated in panel with selected item highlighting (the darker gray you currently use in #2257). So when a mouse user clicks on an annotation item in the panel, or a keyboard users hits Enter while focused on an annotation item in the panel, the canvas anno border changes to yellow, and the panel item area is highlighted with the darker gray.

## Examples
Hopefully these will clarify the guidelines above.

### Highlight all OFF, hover/focus one anno item
User is mousing over, or with the keyboard has arrowed into (but not pressed Enter), the sixth annotation:

<img width="652" alt="OFF-hover-none-selected" src="https://user-images.githubusercontent.com/101482/55494927-a75e5500-55f0-11e9-8d9e-e635865f9696.png">

### Highlight all OFF, selected one anno item
User has clicked on, or with the keyboard has pressed Enter on, the sixth annotation:

<img width="652" alt="OFF-one-selected" src="https://user-images.githubusercontent.com/101482/55495260-58fd8600-55f1-11e9-9eee-fe5a2439e282.png">

### Highlight all OFF, selected one anno item, hover/focus one anno item
After selecting the sixth annotation, the user is mousing over, or with the keyboard has arrowed into (but not pressed Enter), the second annotation:

<img width="652" alt="OFF-one-selected-one-highlighted" src="https://user-images.githubusercontent.com/101482/55495355-8c401500-55f1-11e9-8680-7d255419d0dc.png">

### Highlight all OFF, selected three anno items
Here the user has selected three different anno items, by clicking on each one, or with the keyboard arrowing into and pressing Enter on each one:

<img width="652" alt="OFF-Select-three" src="https://user-images.githubusercontent.com/101482/55495501-e2ad5380-55f1-11e9-94f3-2f82e7ad3b3b.png">

If the user were to click, or arrow into and press Enter, on one of the selected anno items, it would deselect, removing the corresponding panel highlight and the yellow border on the canvas.

### Highlight all ON
With the Highlight all toggle set to on, all of the annotations on the canvas are highlighted. Note that none of the panel anno items are highlighted, because when turning the toggle on the user can't at the same time be hovering over, or have arrowed into, one of the panel annotations. 

<img width="652" alt="ON" src="https://user-images.githubusercontent.com/101482/55495772-80088780-55f2-11e9-8f97-5957f4f6d368.png">

### Highlight all ON, hover/focus one anno item
If after turning on the Highlight all toggle, the user mouses over, or with the keyboard arrows into one of the panel annotations, the anno item gets the hover/focus highlighting (but there is no change to the corresponding canvas annotation indicator, because it is already shown in blue):

<img width="652" alt="ON-highlight-one" src="https://user-images.githubusercontent.com/101482/55496021-fdcc9300-55f2-11e9-9a16-e46b1101e2d6.png">

### Highlight all ON, selected one anno item
If the user then clicks on, or presses Enter on, one of the panel annotations, it is shown with the selected highlighting and the corresponding canvas annotation border is changed to yellow:

<img width="652" alt="ON-select-one" src="https://user-images.githubusercontent.com/101482/55496197-5439d180-55f3-11e9-9eab-4b1dba16cb49.png">

### Highlight all ON, selected three anno items
If the user goes on to click on, or press Enter on, two additional annotations in the panel, they are similarly shown as selected:

<img width="652" alt="ON-select-three" src="https://user-images.githubusercontent.com/101482/55496285-89deba80-55f3-11e9-9a13-f7b2a03e9674.png">

If the user was to turn off the Highlight all toggle in state above, the selected annotations would remain (the selected highlighting of the three on the panel and the corresponding yellow borders on the canvas) but the blue highlighted borders on the canvas would go away.

**Comment by jkeck** [comment]
Hmm, let me get this PR that I have doing the click behavior described (because I think there is an improvement here).

I'm thinking the distinction between highlighted and selected annotations may be best spun out as a separate follow on issue.

**Comment by ggeisler** [comment]
Okay, makes sense. I'll create a new ticket and copy the mockup/description section to it.
