### ISSUE TITLE
Update instructions for embedding Mirador in React app

### ISSUE THREAD

**Issue by charbugs** [ProjectMirador/mirador#2627]
Is there a special reason to suggest using ES modules to embedd Mirador in a React app? I think this approach is not mature yet and people run into issues (#2497, #2600, #2620). There is a simpler solution to embed M3 in React: https://codesandbox.io/s/4x4vn4o4m4. I would like to update the wiki page and suggest this approach, rather then using ES modules.

**Comment by mejackreed** [comment]
Could/should we have both approaches? @gigamorph I think originally wrote those instructions. Though, your approach does make it a lot easier.

**Comment by charbugs** [comment]
> Could/should we have both approaches?

Ok!

**Comment by broadwell** [comment]
Just chiming in belatedly to say that @charbugs's suggested method is quite similar to the approach we were using to embed Mirador 2 into our app, and it generally worked quite well there. That said, we're noticing some scenarios for which having more low-level access to Mirador 3 and especially the Redux store would help us build some better features, so I'm definitely in favor of having both approaches.

**Comment by mejackreed** [comment]
Totally understand. You do have some access to the redux store in the approach suggested by @charbugs . You have access to read the store and dispatch actions. Let us know if that is unclear or what additional things might be nice. Thanks for your feedback again!

**Comment by broadwell** [comment]
I have to confess that it's not immediately obvious to me how to access the redux store in [approach 1](https://github.com/ProjectMirador/mirador/wiki/M3-Embedding-in-Another-Environment) (which looks like @charbugs's suggested approach).

In any case, our motivating feature is being able to parse a manifest's JSON and then to update its viewer window to display a canvas in the middle of the sequence, rather than the first one. This works quite well via a redux subscription and state updates with approach 2.

**Comment by mejackreed** [comment]
Thanks for that understanding @broadwell . I've forked the original example into something else to demonstrate state subscription and dispatching. 

https://codesandbox.io/s/mirador-react-example-with-state-subscription-dispatch-ty9nj

Does this approach give you some of what you need?

**Comment by broadwell** [comment]
@mejackreed yes! That does most of it, and probably it even gives us the extra bit we're currently implementing via approach 2 -- finding and displaying the middle canvas of each manifest -- if the state returned by `getState()` is directly modifiable.

If that's the case, then I guess the remaining benefits of using approach 2 are the performance/consistency gains from keeping the redux store in a higher-level component? Whereas approach 1 seems a bit more streamlined and potentially more maintainable, so that would be a tradeoff.

FYI, you can see what we're trying to do by visiting [this link](https://sul-cidr.github.io/scriptchart/viewer/?mss=BL.%20Add.%2007158|BL.%20Add.%2012148|BL.%20Add.%2012149|BL.%20Add.%2012150|BL.%20Add.%2012151&letters=He%20(Round)|Kaph%20(Final)|Alaph%20(Angular)&examples=3&opts=amhm) and then clicking over to the "Manuscripts" tab after the options menu and table have auto-loaded.
