### ISSUE TITLE
Positioning of "Start Here" and "Add Resource"

### ISSUE THREAD

**Issue by ahankinson** [ProjectMirador/mirador#2662]
In an empty mirador instance the "Start Here" button is in the top-left. This opens up a viewer to add a resource, but the "Add Resource" button is in the bottom-right. This means the user has to move their mouse the furthest distance on any screen to accomplish a task that is likely to happen in succession. 

Given that the user is then prompted to add a resource in a text box at the bottom, and that the resource they add goes at the top of the list, this means that actions and their results happen all over the screen.

Perhaps the "Add Resource" button and the text box could be moved to the top of the screen, which would then add a resource to the top of the list.

**Comment by ggeisler** [comment]
@ahankinson I definitely understand your reasoning. I believe we considered locating the "Add Resource" button at the top of the page, for the reasons you bring up, but ultimately didn't because:

- Putting the Add Resource button at the top of the page takes real estate; effectively all the object rows in the list would move down one row's worth of vertical space further down the page.
- At least for some implementations, we expect many users will only be selecting from objects available in the catalog, and not manually adding additional resources. So making all users see the Add Resource button, when that button might only be used by a minority of users, seems like it might not be a good tradeoff.

That soundness of that rationale depends lot on who the expected users are for a given implementation. If many of the users will be frequently adding new resources (as many of us developing or implementing Mirador do), then I definitely see the argument for putting the button at the top of the page. But ultimately we're developing Mirador for real end-users, who might not have the same need for frequently adding new resources, so keeping the button visible but out of the way of their normal Mirador activity seems like a reasonable tradeoff.

I don't think we're dead set on keeping the button at the bottom.  Maybe as we see how people are implementing Mirador 3 and understand their users better we can reconsider the button location.

**Comment by ggeisler** [comment]
I suggest we close this ticket and we can reopen if and when we hear more concerns about the placement of the "Start Here" and "Add Resource" buttons. As I mention in my previous comment, the design is not as simple as it might seem on first glance, and it is not clear to me that there is an obvious better approach. I'd rather re-open this ticket in the future if necessary than have it sit open when there is no apparent need or motivation for anyone to work on a better solution.

**Comment by camillevilla** [comment]
Closing per Gary's recommendation. I think there may be an opportunity to develop an alternative UI for adding resources as a plugin. @ahankinson If you would be interested in working on this as a plugin, please join us at a [bi-weekly Mirador community call](https://iiif.io/community/groups/) or #mirador-dev in [IIIF slack](http://bit.ly/iiif-slack).
