### ISSUE TITLE
Content search clear interaction should clear results and search box

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador#2676]
The clear action should be triggered by a button:

<img width="339" alt="Screen Shot 2019-06-11 at 9 19 13 AM" src="https://user-images.githubusercontent.com/101482/59289203-5723f480-8c2a-11e9-80a0-122e70ed0ac3.png">

- [x] Clear button is the string "clear" + the clear icon.
- [x] Clear icon is the `highlightOffSharp` icon: https://material.io/tools/icons/?search=highligh&icon=highlight_off&style=sharp.
- [x] Give button 20px left margin.
  * Used `theme.spacing` here instead, let me know if that looks okay
- [x] When the clear button is selected, the top panel is cleaned up (remove the clear button, any results pagination controls, and the search term from the search box).
- [x] When the clear button is selected, any result items shown in the panel are removed so the panel  body area is empty:

<img width="339" alt="Screen Shot 2019-06-11 at 9 20 13 AM" src="https://user-images.githubusercontent.com/101482/59289580-38722d80-8c2b-11e9-8959-271fe27b7ece.png">

**Comment by mejackreed** [comment]
@ggeisler Should we use a MUI chip here?
![Screen Shot 2019-06-12 at 9 43 21 AM](https://user-images.githubusercontent.com/1656824/59365862-899b2380-8cf6-11e9-850d-9e3c5e6e3838.png)

https://material-ui.com/components/chips/

**Comment by ggeisler** [comment]
I guess we can try it, since it's probably quicker to implement than the custom button.

I'm a little worried that the extra chrome associated with the chip (the background or border) might make it feel more dominant than it needs to be:

<img width="326" alt="Screen Shot 2019-06-12 at 8 49 21 AM" src="https://user-images.githubusercontent.com/101482/59366448-2ce83a80-8cef-11e9-9c74-7d5c4d047e0b.png">

But if you want to try it and we can evaluate whether it works or not after seeing it in context, that would be great. I'd go with the variant similar to my mockup above (outlined, secondary color, probably `small`).
