### ISSUE TITLE
Add padding to search input in Search panel header

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador#2738]
In its initial, empty state, the search input is flush against both the bottom of the search panel header and the right edge of the panel header. 

<img width="318" alt="Screen Shot 2019-06-18 at 9 07 34 AM" src="https://user-images.githubusercontent.com/101482/59701151-c90bb900-91a9-11e9-8f15-81dcc899bd14.png">

It would look better with some whitespace between the edges of the input and the panel:

<img width="318" alt="Screen Shot 2019-06-18 at 9 07 18 AM" src="https://user-images.githubusercontent.com/101482/59701162-d0cb5d80-91a9-11e9-934e-f290d40c8c44.png">

To get the layout in the screenshot above, I updated the `MuiFormControl-root` div at the top of the `form` element holding the input like this:

- [ ] `padding-right: 12px;`
- [ ] `padding-bottom: 8px;`

Although someone more familiar with the code might see better/more consistent ways to achieve the same effect.

**Comment by jvine** [comment]
When the panel is on the bottom the added padding changes the overall height of the panel and the alignment of the other elements, so it looks a bit crooked to me. 

<img width="545" alt="Screen Shot 2019-06-18 at 9 52 49 AM" src="https://user-images.githubusercontent.com/6945691/59703532-e4c58e00-91ae-11e9-8244-57c370b87b20.png">
<img width="501" alt="Screen Shot 2019-06-18 at 9 54 28 AM" src="https://user-images.githubusercontent.com/6945691/59703606-18a0b380-91af-11e9-9b16-f35fc1a66e46.png">

On the Index panel, the padding around the dropdown box was finally achieved by giving `div.mirador-companion-window-title-controls` `min-height: 48px;` and `align-items: center;`.  The problem is the search box itself is 48px high, so the alignment doesn't help.

Wondering if there's some way that we can get consistency of header height (at least in the horizontal layout) and spacing across panels...?

**Comment by ggeisler** [comment]
The panel alignment seems way off to me when you widen the panel or move it to the bottom currently, without the suggestion I made above. For example:

<img width="755" alt="Screen Shot 2019-06-18 at 10 04 31 AM" src="https://user-images.githubusercontent.com/101482/59704251-7c77ac00-91b0-11e9-94e0-7a3f0e8c2fe4.png">

---

<img width="1018" alt="Screen Shot 2019-06-18 at 10 03 37 AM" src="https://user-images.githubusercontent.com/101482/59704265-84375080-91b0-11e9-84dc-a9d7c5c7051f.png">

---

So I was just trying to get the default layout looking better, and figured we'd address the other cases later. That said, if we can find a more general solution to get consistency in panel headers, that would be great.
