### ISSUE TITLE
Add option to remove WindowSideBar menu button

### ISSUE THREAD

**Issue by surreal8** [ProjectMirador/mirador#2881]
Related to #2879, we would like the ability to remove the sidebar menu button.

**Comment by ggeisler** [comment]
@surreal8 Can you include a screenshot showing which UI element you are proposing to make configurable with this issue? I'm getting confused because in this ticket you're proposing to make configurable "WindowSideBar" and in the code associated with #2879 you previously added a configuration for `allowWindowSideBar`. 

I'm sure it makes sense but after a couple of months not working on Mirador and in my role where I think about things more from a UI and not a code perspective, I could use clarification on which element you are actually proposing to make configurable here.

**Comment by ggeisler** [comment]
@surreal8 Ignore my comment above, I see what's going on now. I got your PR from the other day mixed up with the PR that addresses this issue. Sorry!

**Comment by surreal8** [comment]
no problem @ggeisler!
