### ISSUE TITLE
Support for multilangual manifests?

### ISSUE THREAD

**Issue by nvanderperren** [ProjectMirador/mirador#2883]
Hi, not sure if this is a duplicate issue (sorry if that's the case).

I was wondering if M3 supports multilangual manifests (for example, metadata values in two languages)?

I've got this manifest: https://nvanderperren.github.io/IIIF-examples/multilangual/manifest.json. It shows the Dutch title and Dutch description and the English metadata values, regardless of whether the workspace language is English or Dutch.

Oddly enough, the attribution value is shown in the correct language (English if the workspace language is English, Dutch if the language is Dutch)

I don't think there's a problem with the manifest, since it's validated succesfully.

**Comment by camillevilla** [comment]
@nvanderperren Yes! Multilingual metadata is now better supported. Mirador tries to match the UI language. In [this example](https://github.com/ProjectMirador/mirador-workshop/pull/10) I have enabled a setting so you can view metadata in two languages at once (admittedly this feature could use more design polish). 
![Screen Shot 2020-12-04 at 11 28 44 AM](https://user-images.githubusercontent.com/5402927/101206595-33c1e600-3624-11eb-9485-321dd10e60ce.png)


Hope this helps! And please feel free to file a new ticket if you have any feedback. 

Side note:
I noticed that your manifest is loading metadata, but the image is not rendering because the image service is at an HTTP address. 
```
Blocked loading mixed active content “http://imagehub.vlaamsekunstcollectie.be/iiif/2/100000022/info.json”
```
