### ISSUE TITLE
Ability to initialize Mirador w/ sidebar visible but all panels collapsed by default

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#3000]
I was wondering if it is possible to initialize Mirador with the following settings: window in gallery mode / window sidebar visible / all sidebar panels collapsed by default.

A use case for this would be: I have embedded into my web application a Mirador instance that shows different kinds of objects depending on the page you are on (a manuscript, a printed book, a thematic collection of images, with potentially hundreds of them). 
In this context, the most appropriate default view for all these objects is the Gallery mode, which allows users to have an immediate overview of the contents and browse through it quickly. 
Secondly, I'd want the window sidebar to be visible but all panels collapsed by default, for one main reason: since most of the Manifests come from the outside (they are not produced by the web application), I cannot set in advance the most suitable panel to be opened by default, because this depends on the Manifest itself and what the user is most interested in. But at the same time I do not want to "hide" the sidebar and force users to click on the "hamburger" toogle button every time they open a new page. A secondary reason is that I want the Gallery view to be as wide as possible and not lose space on the left by having a random (and potentially useless) panel always opened on the left.

So having the sidebar visible and all panels collapsed by default allows to:
1/ save space into the Mirador viewport in its default view
2/ inform the user of the different panels available for a given object (relying on the icons' affordance), without having to choose one panel arbitrarly

It may be seen as quite specific use case, and I think it is, but potentially more widespread than we think (?).

**Comment by cbeer** [comment]
@ggeisler I'm assuming your 👍 is  an endorsement to support this behavior? After expanding the buttons, the default state will be something like:

<img width="131" alt="Screen Shot 2020-05-08 at 07 40 23" src="https://user-images.githubusercontent.com/111218/81416856-30529480-90ff-11ea-8519-432ba3f942bf.png">

And once you click a sidebar, you're back in the normal flow where you can only collapse it and not remove it entirely.

**Comment by ggeisler** [comment]
@cbeer Yes I was indicating I think we should support @regisrob's use case because I think it could be useful for more than just his implementation. It's not clear to me from your description how your implementation works, however. You say "After expanding the buttons" things will look like your screenshot. But I'm not sure what buttons you're referring to?

If by "expanding" you mean selecting the hamburger icon, I don't think that is what the use case described. My understanding is that the goal is for the initial display is to show the sidebar, just that no sidebar menu category is selected and no sidebar panel is open.

Also, from your screenshot it looks like the About menu item is shown as highlighted (gray background). The default state wouldn't show that, I assume? Is this just because you were hovering over that menu item when making the screenshot, maybe?

Maybe your implementation works exactly like I'm suggesting it should, it's just not clear to me from your description.

**Comment by cbeer** [comment]
You're right, I configured the sidebar off by default, but you could show it. I guess I'm confirming starting the sidebar is a completely blank state is ok (instead of, say, initializing it with an active button but a hidden companion window)

![2020-05-08 09-15-14 2020-05-08 09_16_45](https://user-images.githubusercontent.com/111218/81425560-a9a4b400-910c-11ea-9b32-508fc4485693.gif)

**Comment by ggeisler** [comment]
Yes, I think starting with the sidebar in a blank state (visible, but with no sidebar menu item selected) is what @regisrob is after, and I thought about whether this would raise any UX concerns and couldn't think of any.

**Comment by jvine** [comment]
Agree. This was one of the initial designs, so I think we thought it through previously. It looks correct to me.
