### ISSUE TITLE
Support for virtual ruler

### ISSUE THREAD

**Issue by snydman** [ProjectMirador/mirador#305]
parity with 1.0rc

**Comment by markmatney** [comment]
The organization that is funding UCLA Library's Mirador project ("Sinai Palimpsests") are interested in this feature. Are the "help wanted" label and "2.1 milestone" designation accurate (the [Mirador Plan 2016](https://docs.google.com/document/d/1bVwrOHiM7EvVxl4Ogy7stIH0-R_GBXF7vuAJvYxPhG0/edit#heading=h.6csfyv1s2tkj) does not list the feature as a release priority), and can anyone speak on the possibility of the feature being added to an upcoming release?

**Comment by markmatney** [comment]
I've implemented a prototype (using [this OpenSeadragon plugin](https://github.com/NIST-ISG/OpenSeadragonScalebar) as the base) to fit the use cases for UCLA LIbrary's Mirador project. You can see a demo of it [here](https://drive.google.com/file/d/0B_xDW0hVa9VzS3ZIZEhqdmVnSVE/view?usp=sharing). The numbers on the ruler are useless right now, since I haven't configured it to grab the physical dimension data yet.

In the interest of future development, I also created a [design document](https://docs.google.com/document/d/19QQPV4DTMCa4BZohrmTEyIbkM2EkiXcWqo79ePcozQA/edit?usp=sharing) that describes a UI for the ruler that _I'd_ like to use. Please feel free to share, comment, or edit. If there's time at an upcoming community call, I'd like to discuss this doc.

**Comment by azaroth42** [comment]
:+1: ! 

The physical dimension data should be provided in the manifest as per:  
  http://iiif.io/api/annex/services/#physical-dimensions

**Comment by markmatney** [comment]
Got it. I am working on adding that functionality, as well as reorganizing my code.

**Comment by aeschylus** [comment]
Very cool. I can see this being merged in soon from a PR if we can get the new menu in. I left a few comments in the design doc. See: https://docs.google.com/document/d/19QQPV4DTMCa4BZohrmTEyIbkM2EkiXcWqo79ePcozQA/edit#heading=h.4c7gfqbeegc

**Comment by markmatney** [comment]
Update: I have reorganized my code into a "plugin" (https://github.com/UCLALibrary/mirador-ruler), making it one of two ruler plugins (that I know of) (https://github.com/dbmdz/mirador-plugins/tree/master/PhysicalRuler)

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

Considerable effort went into improving the plugin system for Mirador 3. If you're interested in working on plugin development, please join us at a [bi-weekly Mirador community call](https://iiif.io/community/groups/) or #mirador-dev in [IIIF slack](http://bit.ly/iiif-slack).
