### ISSUE TITLE
Accessibility audit: canvas elements

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3107]
> The individual pages of the digitised material are each integrated via a canvas element. These do not have an alternative description in text form that describes the content of the image in short form.
> An easy way to do this is to add the aria-label="digitized view" attribute to the canvas element, as well as an aria-describedby attribute that references the page title below the browse buttons supplement.
> In addition, the canvas element must be marked   as a graphicusing role="img".

**Comment by jvine** [comment]
Tested, and it turns out just what they said:

- add an ID to the `<div>` with `class="mirador-osd-info"` (contains the canvas count and label)

- to the `<canvas>` element, add:
   - `role="img" `
   - `aria-label="digitized view" `
   - `aria-describedby="id-of-mirador-osd-info" `

(Sometimes the `aria-label` assigned to the containing `<section>` is read instead of the `aria-describedby` on the `<canvas>`, but I think that's partly my maladroitness with the SR. Also, possibly the `aria-label` to `aria-labelledby` change proposed in #3123 will solve this.)

**Comment by cbeer** [comment]
Is there any way to get away without touching the `<canvas>`? I'm pretty sure that's coming out of openseadragon.
