### ISSUE TITLE
Accessibility audit: <main> usage

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3114]
> The main element should contain only the main content, and should not include workspace navigation. This nav element must therefore be placed outside the main element. See also HTML specification: https://www.w3.org/TR/html52/grouping- content.html#the-main-element
> 
> Note: The main navigation has an aria- label attribute in its enclosing nav element with the label "Workspace". This label is identical to that of the main area main. It is recommended to rename the main navigation label (e.g. to "Workspace navigation") in order to identify the areas easily and clearly.
>

**Comment by jvine** [comment]
Move the `<nav>` that's immediately inside `<main>` to outside (preceding) `<main>`.

Change the `aria-label` on the `<nav>` to "Workspace navigation".

_(The word "navigation" was removed in a previous issue because in some modes the SR already announces "navigation" for `<nav>` and it was seemed redundant. In case anyone wonders.)_
