### ISSUE TITLE
Offer a way to export/import plugin state along with workspace

### ISSUE THREAD

**Issue by lutzhelm** [ProjectMirador/mirador#3137]
If a plugin has its own state, at least a part of that state might be of interest when exporting, sharing or importing a workspace.

* Plugins could indicate which part of their state should be exported by providing one or more paths for their state tree or by providing a specific selector.
* Reducers of exportable plugins would have to handle the `mirador/IMPORT_MIRADOR_STATE` action.
* Imports in workspaces without that specific plugin would simply have to ignore the plugin state on import.

**Comment by cbeer** [comment]
I've put up  a thought in #3138. Instead of providing a selector, it adds configuration for which stems to export with some basic filtering. Having plugins provide a selector presented some challenges (how to provide  it; what if plugins want multiple  stems or conflict; etc), although  a plugin that needs more advanced exports could now wrap the WorkspaceExport component and do.. anything.
