### ISSUE TITLE
BUG? index thumbnails not loading for memphis

### ISSUE THREAD

**Issue by mprove** [ProjectMirador/mirador#3183]
- load https://www.e-rara.ch/i3f/v20/11583123/manifest into https://mirador-dev.netlify.app/__tests__/integration/mirador/
- switch to index view
=> index thumbnails don't load. they show broken [?]-icons instead.

why? Is this a Mirador3 issue?

![mirador3-memphis-index](https://user-images.githubusercontent.com/1712125/86324679-37011200-bc3f-11ea-97e9-a09b2d430f04.jpg)

**Comment by mprove** [comment]
Is this the same? #3038

**Comment by mejackreed** [comment]
No, I think it is an issue with the image server from e-rara.ch.

These images are not requestable for some reason: https://www.e-rara.ch/zut/i3f/v20/11583143/full/!120,120/0/default.jpg

**Comment by mprove** [comment]
follow'up with ETH >> https://twitter.com/chronohh/status/1278679986476646400

**Comment by camillevilla** [comment]
This is a spec compliance issue with e-rara's image server. The manifest you posteed advertises using [Level 2 compliance](https://iiif.io/api/image/2.1/compliance/#size). This means the server _should_ support `sizeByConfinedWh` (`!120,120`, or `!w,h`). Currently, the image request returns a 500 error: https://www.e-rara.ch/zut/i3f/v20/11583143/full/!120,120/0/default.jpg

@mprove I'm going to close this issue since this cannot be resolved by the Mirador team. Please feel free to refer ETH to this issue.
