### ISSUE TITLE
mirador.js file doesn't exist in release version

### ISSUE THREAD

**Issue by ydvelaitzky** [ProjectMirador/mirador#3205]
I want to embed the mirador  viewer in my asp.net application
I downloaded the zip file of mirador 3 from that latest release (in https://github.com/ProjectMirador/mirador/releases/tag/v3.0.0-rc.3)  , but now I am embarrassed: The release contains  many js  files and more... , Which file from them I would take? The mirador demo source – uses a file by the name of- mirador.min.js (in developer toolbar can see it) but this file does not exist in the dowloaded folder. (By the way - reference my project to the source file of the demo- worked for me, but I guess this way is not recommended)
Can you please help me? Thank you!

**Comment by mejackreed** [comment]
Hi @ydvelaitzky thanks for filing the issue!

The files in the npm js package are available for display here: https://unpkg.com/browse/mirador@3.0.0-rc.3/

`dist/mirador-min.js` is the file you are looking for if you are looking to use the umd build.

We recommend using Mirador from the npm package rather than downloading the release from GitHub. Are you able to install it via npm?

**Comment by ydvelaitzky** [comment]
Thaks for your quick reply
Why  should I use the npm package instead of simply download the mirador.js from the dist folder in the unpkg site? Am I missing  something ? Additionally , Do  I need all the files in dist  folder or mirador.js is enough?

**Comment by mejackreed** [comment]
You can most definitely download the file you would need `dist/mirador-min.js` in this case.

Or you can even just link it like this in your source:

```html
<script src="https://unpkg.com/mirador@rc/dist/mirador.min.js"></script>
```

Using the npm package gives you a way to update Mirador to new versions without having to manually redownload it.
