### ISSUE TITLE
Logo not showing in iiif presentation 3.0 - Fudan University

### ISSUE THREAD

**Issue by stone12379** [ProjectMirador/mirador#3269]
- Yes
- URL: https://devcn.api.gushuhua.org/presentation/6e3d5b5b-84b1-4786-a397-9b8ead6f2ead
- Manifest hosting institution: Fudan University

### Observed behavior
- Description: Logo not showing
- Screenshots / screen recordings / GIFs
- Errors or warnings from the UI, developer console, or the [IIIF Presentation Validator](https://iiif.io/api/presentation/validator/service/)
```
Paste errors here if needed, otherwise delete
```

**Comment by camillevilla** [comment]
@stone12379 [This manifest](https://devcn.api.gushuhua.org/presentation/6e3d5b5b-84b1-4786-a397-9b8ead6f2ead) does not have a `logo` property, which is why a placeholder is displayed. 

<img width="1025" alt="Mirador" src="https://user-images.githubusercontent.com/5402927/94736733-8f6cac00-0321-11eb-9028-24570412101a.png">

Please see information on that property here:
https://iiif.io/api/presentation/3.0/#logo

Here's an example from Stanford:
https://purl.stanford.edu/fr426cg9537/iiif3/manifest
```json
"logo": [

    {
        "id": "https://stacks.stanford.edu/image/iiif/wy534zh7137%2FSULAIR_rosette/full/400,/0/default.jpg",
        "type": "Image",
        "service": [
            {
                "id": "https://stacks.stanford.edu/image/iiif/wy534zh7137%2FSULAIR_rosette",
                "type": "ImageService2",
                "profile": "http://iiif.io/api/image/2/level2.json"
            }
        ]
    }

],
```
