### ISSUE TITLE
No thumbnails in Angular project (in Gallery view, bottom and right) Mirador2/3

### ISSUE THREAD

**Issue by daynewss** [ProjectMirador/mirador#3303]
- I am the author or maintainer of this manifest: No
- URL: <https://iiif.harvardartmuseums.org/manifests/object/299843>
- Manifest hosting institution <https://www.harvardartmuseums.org/>

### Observed behavior
- Description: (All thumbnails are not loading in Gallery view, Bottom or Right)
![image](https://user-images.githubusercontent.com/2485816/97170255-04ea6180-1794-11eb-840c-838953ce857a.png)

Me and colegues on other project, that must use IIIF and Mirador, can't see thumbnails. Anywhere - in Gallery mode, on the bottom or right of the window. Even with manifest from mirador home page. Both projects are Angular projects. Angular versions are 9 and 10.

[link to Angular Mirador demo project on github](https://github.com/daynewss/mirador-demo)

**Comment by mejackreed** [comment]
Thanks for filing @daynewss . I think this is a similar issue to https://github.com/ProjectMirador/mirador/issues/2961 

For some reason in Angular projects the [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) API that Mirador uses to lazy load thumbnails fails to be triggered. I'm not sure what the root cause of this is and I have tried debugging before. 

Do you know if there are any other issues around Angular + Intersection Observer?

**Comment by mejackreed** [comment]
@daynewss here is a workaround that you can use:

https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-my-angular-project-that-uses-mirador-3-is-not-displaying-thumbnails-how-can-i-get-this-to-work

**Comment by daynewss** [comment]
Thank you very much. I'll try tommorow and inform our other development group.
