### ISSUE TITLE
Mirador 3 BUG Mirador viewer navigates only throught pages 1 to 10

### ISSUE THREAD

**Issue by daynewss** [ProjectMirador/mirador#3346]
- I am the author or maintainer of this manifest: Yes
- URL: https://eaistest.asseco.lt/viewer-api/rest/2/manifest
- Manifest hosting institution: OFFICE OF THE CHIEF ARCHIVIST OF LITHUANIA / under development 

### Observed behavior
- Description: Mirador viewer navigates only throught pages 1 to 10. If I select page from list on the left side of viewer, then it takes me to page that I've selected, but it shows wrong numbers in navigation panel on the bottom of the viewer. 
Let's say viewer opens page 1. If I go through"Next item" everything works fine until page 10. On the page 10 if I press "Next item" it will throw me to the page 2. I don't understand why, but it will take me to page 2. If i select page 24 from the list, viewer will take me to canvas 24, but page number on the bottom of the page will show "4 of ..." and if I click "Next item" viewer will take me to canvas 5. If I select page 57 and press "Next item" viewer will take me to page 8. 

- Screenshots / screen recordings / GIFs
![mirador](https://user-images.githubusercontent.com/2485816/99386361-06163680-28db-11eb-82e2-0d5232b3ce57.jpg)

- There are no errors or warnings. We use Cantaloupe 4.1.6 for images server.

**Comment by cbeer** [comment]
Hi @daynewss  -- I took a little look into this. I believe the problem is caused because your canvas IDs in that manifest are not URIs, just plain strings (e.g. `LVIA_KA_3002_26_3/canvas-211`). Per the IIIF spec:

> . Canvases must be identified by a URI and it must be an HTTP(S) URI
https://iiif.io/api/presentation/3.0/#53-canvas

There's some URI normalization code in [manifesto.js](http://github.com/iiif-commons/manifesto/) that expects URIs, and ends up normalizing  `LVIA_KA_3002_26_3/canvas-1` and `LVIA_KA_3002_26_3/canvas-11` to the same value:

```
  static normaliseUrl(url: string): string {    url = url.substr(url.indexOf("://"));
```
https://github.com/IIIF-Commons/manifesto/blob/master/src/Utils.ts#L116
