### ISSUE TITLE
metadata slideout area

### ISSUE THREAD

**Issue by yulgit1** [ProjectMirador/mirador#3408]
User comment: The metadata area (opened via the hamburger menu at top left) is rather narrow. Could it be slightly wider? Or could the width respond to user adjustments?

**Comment by yulgit1** [comment]
User comment: Is it possible to adjust the typography for the metadata area. The font sizes seem to fluctuate there isn’t much distinction between field label and field data.

**Comment by ggeisler** [comment]
@yulgit1 

> User comment: The metadata area (opened via the hamburger menu at top left) is rather narrow. Could it be slightly wider? Or could the width respond to user adjustments?

The window side panels are currently user-adjustable. You can drag the side of the window to resize it to be wider or narrower.

**Comment by ggeisler** [comment]
@yulgit1 

> User comment: Is it possible to adjust the typography for the metadata area. The font sizes seem to fluctuate there isn’t much distinction between field label and field data.

The typography in the window side panels has an intentional design. There are many types of information that are displayed in this panel (section labels, section titles, object title, field label, field values) and font size and weight are intentionally and consistently applied to distinguish different types of information.

I agree that the distinction between the field label and field value is subtle (the label is bolder and slightly smaller than the value) but that has to be balanced with the need to not reuse styles applied to other types of information in the same panel. I think it's more challenging that a casual viewer might think.

That said, it someone has ideas for how to improve the typography that still clearly distinguishes all the different types of information displayed in the panel and can convey that through mockups or something, I'm sure the community would be open to considering it.
