### ISSUE TITLE
How to add watermark image on IIIF image in mirador?

### ISSUE THREAD

**Issue by ChayaBer1** [ProjectMirador/mirador#3556]
Is there a way of adding watermark image on some specific images according to a condition?

**Comment by arthytrip** [comment]
Hello @ChayaBer1 
I'm interested too. Have you found any solution?

**Comment by jbaiter** [comment]
I don't think this makes much sense in a viewer, the client can always just request the image from the IIIF Image API and get it without the watermark.
If you really have to do watermarking, the image server is the obvious place to do it.

**Comment by arthytrip** [comment]
Yes I agree.
In fact I am using Cantaloupe 5.0 as image server, but I have to implement a dynamic watermark, a text based on the URL used and/or on other "context key" values.
Unfortunately, it seems impossible to detect most of the "context keys" from Cantalupe's delegates.rb script.
I posted a couple of requests on GitHub and Google Groups but no one replied (see [here](https://github.com/cantaloupe-project/cantaloupe/discussions/598) and [here](https://groups.google.com/g/iiif-discuss/c/rDTQMb1Prng)).
Imho, the problem is that Cantaloupe is not called directly but through Mirador, sending portions of the requested images to it, so Cantaloupe's "contextual keys" are almost all empty.
So, my question here, as a possible alternative.
Thanks in advance for any further suggestions.

**Comment by arthytrip** [comment]
Forget about it.
I solved the problem I had with Cantaloupe, it was simply due to the excessive length of the text strings never displaying on too small images used as an example.
