### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by cbeer** [ProjectMirador/mirador#3602]
After #3601 , we can take the leap to React 18. It should (🤞 ) just be a matter of addressing v17 deprecation warnings.

> ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it’s running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

**Comment by whunter** [comment]
Can someone explain to me how the community is implementing Mirador with React correctly right now? Because of dependency conflicts I'm actually using the `--force` flag to install node packages, which I don't really consider ideal. Is there a clean, correct way that I can add Mirador to my React project without pinning all of my packages back or just rolling the dice with `--force`?
Does anyone have a link to a project repo that's using Mirador in React 18 that I can cheat off of?

**Comment by enriquediaz** [comment]
Hi @whunter 👋 work to get Mirador up to date is still in progress but nearing completion. You'll find the latest work in the [mui5](https://github.com/ProjectMirador/mirador/tree/mui5) branch, where related tests still need to be updated. However, if you're familiar/comfortable with building it & running it locally, it would be GREAT for you to post your experience and impressions in the [Discussion](https://github.com/ProjectMirador/mirador/discussions) section of the project repo to let the contributors know how the community is finding the work!

**Comment by enriquediaz** [comment]
Closing this out because this work was successfully completed per release of [v4.0.0.alpha-1](https://github.com/ProjectMirador/mirador/releases/tag/v4.0.0.alpha-1)
