### ISSUE TITLE
Improve keyboard controls

### ISSUE THREAD

**Issue by snydman** [ProjectMirador/mirador#418]

**Comment by randystern** [comment]
I wish Mirador supported the up and down movement of the displayed image using the arrow keys.

When I try to really read a page, I get down to the bottom of the image window and I need to push the page up so that I can see the text I have not read yet. I would prefer to use the arrow keys -- or to have that as an option.

The two ways of moving the page-image up and down for viewing are, 1) drag with mouse or, 2) to mouse-click inside the very small navigation control within the interface (see attached screenshot).

When I drag the page with my mouse I seem to lose my place. Also, if you are reading more than a few pages, it would be nice to advance forward and backward in the page/image sequence using the keyboard.

Give it a try for yourself. This is a great letter: http://iiif.lib.harvard.edu/manifests/view/drs:23074260$1i

Thanks,

Bill Comstock, Harvard

**Comment by aeschylus** [comment]
Verify this works when we integrate.

**Comment by aeschylus** [comment]
I'm gathering together some of these tickets after seeing a recent pull request. This is worth discussing on some of the upcoming calls from a design perspective.

https://github.com/ProjectMirador/mirador/issues/418
https://github.com/ProjectMirador/mirador/issues/7
https://github.com/ProjectMirador/mirador/issues/572
https://github.com/ProjectMirador/mirador/issues/596
https://github.com/ProjectMirador/mirador/issues/1139

**Comment by aeschylus** [comment]
It's also worth noting that the key design constraint here is how to manage focus, since we have multiple identical objects that might be acted upon with the same commands (windows and each of their components). You can see why this is difficult if you consider that Mirador already supports moving around the canvas, and zooming in and out, using WASD, arrow keys, and the - and + keys. It's difficult to use because the canvas element itself has to "have focus" (in the strict browser/accessibility sense). In @randystern's letter above, for instance, clicking on the canvas, and then using the WASD or arrow keys will let you move around as described, and you can zoom with the -/+ keys.

**Comment by mejackreed** [comment]
This issue has some great historical context, but I believe may not be further actionable with the advent of Mirador 3.
