### ISSUE TITLE
Recommendations for Contributor Guidelines

### ISSUE THREAD

**Issue by pobocks** [ProjectMirador/mirador#514]
This is basically a list of things I needed or wanted to know when starting work, or that I think will make taking contributions easier.
- Coding Standards,  especially an Indent/Trailing whitespace/etc policy.  All that I can find right now is a reference to EditorConfig, and no EditorConfig file - and the indent and whitespace don't seem to be completely consistent project-wide as far as I can tell.  There are a number of existing, freely available, fairly comprehensive policies, so I'm not going to itemize this.
- Possibly covered by the above, but a comment policy (what level of detail and what kind of things are expected to be covered.
- Testing policy, links to doc for karma/etc.
- Browser support expectations, and any polyfills already in use.  A specific issue I've hit - there are console.log calls committed in the code, which will throw in IE<=8
- Some sort of structural document or diagram describing the various objects in the system.
- A list of dependencies with links - you more or less have this by saying "npm and bower," but should have pointers to package.json and bower.json that point them out.
- A communication policy - something like an example format for issues, expected turnaround time for communication on issues, etc.

Does that make sense as a starting point?

**Comment by aeschylus** [comment]
Thanks for this checklist. We are actively working on this. 

I'm currently breaking the wiki section about this out into the developer workflow page and filling out the sections that haven't been completed there. 

Here's what I'm thinking on a few of these things:

JSCS was recently released, enabling automatic style enforcement. We also need to provide a working editorconfig so people can catch any style problems earlier. 

We've mostly switched to the [airbnb style guide](https://github.com/airbnb/javascript) internally at Stanford, and I would like to switch to that, as I have fewer disagreements with it than the idiomatic guide, and JSCS supports it as one of its configuration suites. 

I am in the process of fixing the build process to correctly report tests, and filling out the test suite. We would like to switch over to a test-driven development cycle, but obviously this requires contributors to know how to do that, and we need to support them by having good, fairly complete test coverage to begin with. This includes extending our saucelabs coverage back to the most recent versions of major browsers, as well as the last most recent (so, IE 9+, since very few people have upgraded to 11).

I agree with the need for a "code tour" which explains where to get started, how to think about the operation of the system and major patterns we use.

As far as communication policy, I am also working on a diagram that shows how an issue becomes an accepted feature. One problem with many open source projects is they have no design oversight. This can sometimes work for headless libraries with a fairly well-defined domain and API pattern, like many node modules, but a complete front-end app needs a design step. Not every tweak to animation style, new control element, or menu organisation change should be accepted just because a pull request has  been submitted, even if it is very cleanly coded and well-tested. In the interest of making this transparent, there has been talk of forming a design group composed of people from multiple institutions that validates new user-facing features by comparing them with feedback that has been collected, personas, and current users' existing needs. This would increase the time for features to make it into a release, but will hopefully maintain/increase design quality as use-cases and technology evolve.

The place for all of these things is the wiki. I'll look forward to your feedback once I've filled out the [Developer Tooling and Workflow](https://github.com/IIIF/mirador/wiki/Developer-Tooling-and-Workflow) page a bit more.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

There have been significant changes to the Mirador dev experience (and JS tooling in general!) since this issue was submitted. Fresh feedback is always welcome.
