### ISSUE TITLE
non developer install (docs, data)

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador#521]
On a system that doesn't need npm etc etc, I want to have a downloadable zip of the prebuilt Mirador code to unzip and use.  The README says this is in the latest release, and the content will be in the build directory.

I downloaded the release .zip, and unpacked it. There's no build directory, no index.html, no mirador.min.js...

**Comment by azaroth42** [comment]
After messing around some...
 * Get source code and mirador.zip
 * Unpack mirador.zip into root/build
 * Unpack v2.0.0.tar.gz
 * Copy mirador-2.0.0/images to root
 * Copy mirador-2.0.0/index.html to root

(I also copied fonts and css, not knowing whether they're needed or not)

Still ... one would have thought this would have been checked before a release?

**Comment by aeschylus** [comment]
Working on this now. The zip files are manually added, not generated.

The binaries needed to be refreshed shortly after the launch due to some bugs creeping in that were supposed to have been fixed. It seems I forgot to regenerate the build folder. A large oversight!

In general the build folder needs to be reorganised. In documenting it I will make that reorganisation as part of a 2.0.1 release.

**Comment by aeschylus** [comment]
This is related to #435, which I was unable to reproduce, but perhaps I should try harder.

**Comment by aeschylus** [comment]
Agreed the process should be 
1. Download zip
2. run... it works.
3. copy the files wherever you want into your project. This step is in the worst shape at the moment, since the expected paths are relative. This is essentially dictating a certain folder structure to the end user. Not really "playing nice". The folder paths should be configurable in javascript, or somehow all resources should be completely contained within a black box, although with images this is not really feasible without significantly bloating the build (for instance, with huge dataURIs).

**Comment by mejackreed** [comment]
@azaroth42 this is way simplified for non-developer/end users in Mirador 3. I've created #2761 which will update the README to direct end users.
