### ISSUE TITLE
Large performance hit opening Mirador on a canvas deep in the sequence

### ISSUE THREAD

**Issue by regisrob** [ProjectMirador/mirador#528]
There is a huge performance issue when Mirador is initialized in "ImageView" with a "canvasId". Mirador populates the thumbnails filmstrip starting from the first image in the sequence. Thus the viewer sends as many image requests as there are canvases before the "canvasId". If the "canvasId" is too distant from the beginning of the sequence, the UI gets stuck until the loading is completed (can take a long while) and OSD just fails (zoom view remains empty).

Example : http://iiif.biblissima.fr/manifest/view/ark:/12148/btv1b10520111w/f200

Would it be possible to make the loading process more efficient in this particular case? (i.e. by only loading {n} thumbnails before and after the thumbnail of the canvas given as "canvasId")

**Comment by rsinghal** [comment]
Yes, the filmstrip loading can and should be smarter.

**Comment by aeschylus** [comment]
One option would be to use a method similar to the manifest panel, where each image is created first as a container (so there is an explicit placeholder, rather that a broken image rectangle supplied by the browser). This would allow us to complete the layout without having to load any images in explicitly (since we already known their dimensions). 

The bottom panel should be refactored anyway to get rid of the scrollbar and have a more granular model of its own dimensions (what is/are(bookview) selected, where is my centre, how big am I, have I changed size, etc.). Then the images being loaded can be a function of the panel's dimensions and the items displayed in the main viewport of the window.

**Comment by aeschylus** [comment]
I'm also curious why the main viewport cares at all about which things are loaded already. I think we determined it was a server-side issue, but I'm not sure we went further than that. Whatever we do to fix this, we should make sure it sends out the OSD requests first, and can resolve them asynchronously.

**Comment by rsinghal** [comment]
I think it is a server-side issue.  In @regisrob's example, mirador is making hundreds of calls to the image server for the individual thumbnails, which get queued before the OSD images requests to the same server.  The thumbnail code is supposed to do lazy loading, but that only applies to not requesting the images after the current one, not to the images before the current one.  The isOnScreen function in utils.js, https://github.com/IIIF/mirador/blob/master/js/src/utils/utils.js#L164, needs to be smarter.

**Comment by rsinghal** [comment]
And to your first comment, @aeschylus, we do create the container for each image so there is an explicit placeholder and then determine if the image should be displayed if the placeholder is on the screen.  But, that code is not precise enough in determining if the placeholder is on the screen.

**Comment by aeschylus** [comment]
Related issue: #529

**Comment by rsinghal** [comment]
This needs to be fixed in order to complete #419, otherwise all thumbnails will load in order to load the right most pages.

**Comment by rsinghal** [comment]
After we incorporate OSD collections, create a new module for the filmstrip.

**Comment by rsinghal** [comment]
Use image promises from IIIFML

**Comment by mejackreed** [comment]
This is resolved in Mirador 3 through "windowing" and intersectionobserver.
