### ISSUE TITLE
Viewing many large manifests causes the browser to become slow/unresponsive

### ISSUE THREAD

**Issue by najamansari** [ProjectMirador/mirador#718]
If you load up Mirador with a bunch of collections containing a large number of images (>1000) and start viewing those images, the Mirador viewer and the browser both gradually become slow, specially if the browser has additional tabs/windows opened. Tested on Firefox and Chromium.

**Comment by aeschylus** [comment]
Is this necessary to address in 2.1? I'm going to say defer. On the one hand we need to address the hierarchical loading of collections, so that we only bring in the manifests that are absolutely needed, as they are needed. 

On the other hand there is the lazy-loading issue, with I feel is handled nearly as well as it can be at the moment. The OSD-collections work will improve things with this as well.

However, at the end of the day, the browser has a finite amount of memory. We may want to consider adding a default "max manifests" setting that the user extends at their own risk. A few hundred manifests still runs reasonably well in my experience. The number of images doesn't really matter that much unless it's a truly monumental collection (>3-4000).

What can we do to more granularly quantify this problem?

**Comment by mejackreed** [comment]
This is now addressed in Mirador 3. Closing this issue as it will be unlikely worked on in Mirador 2.
