### ISSUE TITLE
Indicate a canvas has multiple image resources in Thumbnail filmstrip

### ISSUE THREAD

**Issue by rsinghal** [ProjectMirador/mirador#856]
Some sort of visual clue, like a + sign

**Comment by aeschylus** [comment]
I could see this being more confusing than helpful. Why would a user want to know this in the thumbnail view (other than demoing multi-image support, and wanting to select something that showed that feature)?

It might be an example of exposing too much of the model to the user.

**Comment by beaudet** [comment]
Rashmi and I were discussing in the context of a potential drag&drop of thumbnails into the layers tab.  I don't think it's important any longer since the decision was made last week not to drag & drop a canvas thumbnail into the layers tab.   That said, generating a proper thumbnail for a canvas could get trickier as more support for canvas authoring is added to Mirador since the thumbnail supplied with the manifest may no longer be valid after the canvas is modified.
