### ISSUE TITLE
Clicking the "close thumbnail tray" icon causes thumbnail tray to pop up into the canvas. 

### ISSUE THREAD

**Issue by aeschylus** [ProjectMirador/mirador#914]
I think this can be reproduced by creating some slots, which causes the windows to resize.

**Comment by rsinghal** [comment]
Can you include a screenshot?

**Comment by gigamorph** [comment]
It can be easily reproduced from the Mirador demo site. Add any slot, and try to close it by clicking on `X Close`. Instead of closing slot, it opens up the manifest selector panel. Apparently the `a.addItemLink` element is covering the whole slot area and is preventing click events reaching the `a.remove-slot-option` element.

**Comment by camillevilla** [comment]
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.
